package com.jsv.editor;
/* The following code was generated by JFlex 1.4.3 on 15/04/12 19:26 */

import java.io.StringReader;
import com.jsv.data.Variant;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 15/04/12 19:26 from the specification file
 * <tt>C:/Renato/Pessoal/Projetos/RenR3/Ling/scanner.flex</tt>
 */
class AYylex_Old {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\55\1\1\2\0\1\2\22\0\1\55\1\0\1\53\4\0"+
    "\1\52\1\43\1\44\1\50\1\46\1\4\1\6\1\51\1\47\12\3"+
    "\2\0\1\56\1\45\1\7\2\0\1\22\1\14\1\15\1\20\1\24"+
    "\1\17\1\41\1\30\1\16\1\42\1\40\1\25\1\21\1\26\1\34"+
    "\1\36\1\5\1\37\1\23\1\31\1\33\1\32\1\27\1\5\1\35"+
    "\1\5\1\11\1\54\1\12\3\0\1\22\1\14\1\15\1\20\1\24"+
    "\1\17\1\41\1\30\1\16\1\42\1\40\1\25\1\21\1\26\1\34"+
    "\1\36\1\5\1\37\1\23\1\31\1\33\1\32\1\27\1\5\1\35"+
    "\1\5\1\0\1\13\1\0\1\10\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\4\1\5\1\6\1\7"+
    "\2\10\1\11\1\12\1\13\1\14\16\5\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\1\1\25"+
    "\1\26\4\0\1\27\1\0\1\30\3\0\1\31\1\0"+
    "\1\32\2\0\1\33\2\0\1\34\2\0\1\30\1\0"+
    "\1\5\2\0\1\5\2\31\1\33\1\0\3\5\1\0"+
    "\2\5\2\32\2\5\1\0\3\5\1\0\3\5\1\0"+
    "\1\5\1\0\2\5\1\34\1\5\1\34\2\5\1\0"+
    "\1\5\1\0\1\5\1\30\1\35\1\5\1\30\1\0"+
    "\1\5\1\0\1\5\1\0\1\5\1\0\1\5\1\0"+
    "\1\36\1\0\1\37\1\40\1\41\1\42\1\0\1\43"+
    "\1\44\1\0\1\45\1\46\3\0\1\47\1\45\5\0"+
    "\1\50\2\0\1\51\1\0\1\52\4\0\1\53\2\0"+
    "\1\53\1\0\2\47\5\0\1\50\1\52\3\0\1\52"+
    "\10\0\2\5\1\0\1\5\1\0\3\5\1\52\1\0"+
    "\1\5\1\52\1\5\1\45\1\0\1\45\1\5\3\47"+
    "\1\5\1\46\1\0\1\5\1\53\1\5\1\53\1\46"+
    "\2\0\7\5\1\0\3\5\1\0\2\5\1\50\1\5"+
    "\1\51\2\5\1\36\1\54\1\11\1\55\2\0\1\56"+
    "\1\57\2\0\1\55\1\60\1\61\1\0\1\62\2\0"+
    "\1\63\1\0\1\61\1\0\1\61\5\0\1\56\1\0"+
    "\1\55\2\0\1\60\2\0\1\60\1\0\1\63\1\0"+
    "\1\64\1\65\1\0\2\60\1\56\1\55\1\63\3\0"+
    "\1\66\1\67\1\65\2\0\1\57\1\0\2\5\1\60"+
    "\1\63\2\5\1\63\1\57\1\5\1\57\1\0\2\5"+
    "\2\0\2\5\1\55\1\62\1\55\5\5\1\67\3\5"+
    "\1\65\1\5\1\65\1\64\2\5\1\56\1\66\1\61"+
    "\1\70\1\0\1\70\1\71\7\0\1\72\1\73\1\70"+
    "\1\0\1\73\1\0\2\74\1\72\2\0\1\72\1\71"+
    "\2\0\1\75\1\70\1\0\2\74\1\0\1\72\1\74"+
    "\2\70\1\0\1\73\1\5\1\73\1\5\1\72\1\74"+
    "\2\5\1\0\2\5\1\70\5\5\1\71\1\75\3\5"+
    "\2\76\1\0\1\77\1\100\1\101\1\102\1\103\1\104"+
    "\1\0\1\105\1\100\1\101\1\0\1\106\1\0\1\106"+
    "\1\0\1\107\1\76\1\100\1\103\1\106\1\101\1\77"+
    "\1\102\1\104\1\105\1\76\4\5\1\100\1\107\1\110"+
    "\1\0\1\110\1\0\2\111\1\110\1\5\1\110\1\5"+
    "\1\111\1\112\1\0\2\112\1\5\1\0\1\5\2\113";

  private static int [] zzUnpackAction() {
    int [] result = new int[432];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\57\0\136\0\215\0\57\0\274\0\57"+
    "\0\353\0\u011a\0\u0149\0\u0178\0\u01a7\0\u01d6\0\u0205\0\u0234"+
    "\0\u0263\0\u0292\0\u02c1\0\u02f0\0\u031f\0\u034e\0\u037d\0\u03ac"+
    "\0\u03db\0\u040a\0\u0439\0\u0468\0\u0497\0\57\0\57\0\57"+
    "\0\57\0\57\0\57\0\57\0\u04c6\0\u04f5\0\u0524\0\u0553"+
    "\0\u0582\0\u05b1\0\u05e0\0\u060f\0\57\0\u063e\0\u066d\0\u069c"+
    "\0\u06cb\0\u06fa\0\57\0\u0729\0\57\0\u0758\0\u0787\0\u07b6"+
    "\0\u07e5\0\u0814\0\u0843\0\u0872\0\u08a1\0\u08d0\0\u08ff\0\u092e"+
    "\0\u095d\0\u098c\0\u09bb\0\u09ea\0\274\0\u0a19\0\u0a48\0\u0a77"+
    "\0\u0aa6\0\u0ad5\0\u0b04\0\u0b33\0\u0b62\0\u0b91\0\274\0\u0bc0"+
    "\0\u0bef\0\u0c1e\0\u0c4d\0\u0c7c\0\u0cab\0\u0cda\0\u0d09\0\u0d38"+
    "\0\u0d67\0\u0d96\0\u0dc5\0\u0df4\0\u0e23\0\u0e52\0\u0e81\0\u0eb0"+
    "\0\274\0\u0edf\0\u0f0e\0\u0f3d\0\u0f6c\0\u0f9b\0\u0fca\0\u0ff9"+
    "\0\274\0\u1028\0\274\0\u1057\0\u1086\0\u10b5\0\u10e4\0\u1113"+
    "\0\u1142\0\u1171\0\u11a0\0\u04f5\0\u11cf\0\u11fe\0\57\0\57"+
    "\0\u0582\0\u122d\0\u125c\0\u128b\0\57\0\u12ba\0\u12e9\0\57"+
    "\0\u1318\0\u1347\0\u1376\0\u13a5\0\57\0\u13d4\0\u1403\0\u1432"+
    "\0\u1461\0\u1490\0\u14bf\0\u14ee\0\u151d\0\57\0\u154c\0\u157b"+
    "\0\u157b\0\u15aa\0\u15d9\0\u1608\0\u1637\0\u1666\0\u1695\0\57"+
    "\0\u16c4\0\u16f3\0\u1722\0\u1751\0\u1780\0\u17af\0\u17de\0\u180d"+
    "\0\57\0\u183c\0\u186b\0\u189a\0\u18c9\0\57\0\u18f8\0\u1927"+
    "\0\u1956\0\u1985\0\u19b4\0\u19e3\0\u1a12\0\u1a41\0\u1a70\0\u1a9f"+
    "\0\u1ace\0\u1afd\0\u1b2c\0\u1b5b\0\u1b8a\0\u1bb9\0\u1be8\0\u1c17"+
    "\0\u1c46\0\274\0\u1c75\0\u1ca4\0\u1ca4\0\274\0\u1cd3\0\u1985"+
    "\0\57\0\274\0\u1d02\0\u1d31\0\u1d60\0\u1d8f\0\u1d60\0\u1dbe"+
    "\0\274\0\274\0\u1ded\0\u1722\0\u1e1c\0\u1e4b\0\u1e7a\0\u1ea9"+
    "\0\u1ed8\0\u1f07\0\u1f36\0\u1f65\0\u1f94\0\u1fc3\0\u1ff2\0\u2021"+
    "\0\u2050\0\u207f\0\274\0\u20ae\0\274\0\u20dd\0\u210c\0\u11fe"+
    "\0\u213b\0\57\0\u216a\0\u2199\0\u21c8\0\57\0\57\0\u21f7"+
    "\0\u2226\0\u2255\0\u2284\0\u22b3\0\u22e2\0\57\0\u2311\0\u2340"+
    "\0\57\0\u236f\0\u2284\0\u2284\0\57\0\u239e\0\u23cd\0\u23fc"+
    "\0\u242b\0\u245a\0\u22b3\0\u22b3\0\u2489\0\u24b8\0\u24e7\0\u2516"+
    "\0\u2545\0\u2574\0\57\0\u25a3\0\u25d2\0\u25d2\0\57\0\u2601"+
    "\0\u2630\0\u265f\0\u268e\0\u2574\0\57\0\u26bd\0\u26ec\0\u271b"+
    "\0\u2489\0\57\0\57\0\57\0\u274a\0\u2601\0\u2779\0\u2779"+
    "\0\u27a8\0\u27d7\0\274\0\u26ec\0\u2806\0\u2835\0\274\0\u2545"+
    "\0\u2864\0\274\0\u2893\0\u28c2\0\u28f1\0\u2920\0\u294f\0\u297e"+
    "\0\u29ad\0\u271b\0\274\0\274\0\u29dc\0\u2a0b\0\u2a3a\0\u2a69"+
    "\0\u2a98\0\274\0\u2ac7\0\u2af6\0\u2b25\0\u239e\0\u2b54\0\274"+
    "\0\274\0\u2b83\0\u2bb2\0\274\0\274\0\274\0\u2be1\0\u2c10"+
    "\0\57\0\u2c3f\0\u2c6e\0\u2c9d\0\u2ccc\0\u2cfb\0\u2d2a\0\u2d59"+
    "\0\u2d88\0\u2db7\0\57\0\u2de6\0\u2e15\0\u2e44\0\u2e44\0\u2d2a"+
    "\0\57\0\u2e73\0\u2ea2\0\u2ed1\0\u2f00\0\57\0\u2f2f\0\u2f5e"+
    "\0\57\0\u2f8d\0\u2f00\0\u2fbc\0\u2f5e\0\u2feb\0\57\0\u301a"+
    "\0\u3049\0\u3078\0\u30a7\0\u2f2f\0\u30d6\0\274\0\u3105\0\274"+
    "\0\274\0\u3134\0\u3163\0\u3192\0\u31c1\0\u31f0\0\274\0\u321f"+
    "\0\u324e\0\u327d\0\u32ac\0\u32db\0\274\0\274\0\u330a\0\u3339"+
    "\0\u3368\0\u3397\0\57\0\u33c6\0\57\0\u33f5\0\u3424\0\57"+
    "\0\57\0\57\0\u3453\0\57\0\57\0\57\0\u3424\0\u33f5"+
    "\0\u33f5\0\57\0\u3482\0\57\0\u34b1\0\u3424\0\274\0\274"+
    "\0\274\0\274\0\274\0\274\0\274\0\274\0\u34e0\0\u350f"+
    "\0\u353e\0\u356d\0\274\0\274\0\u359c\0\u35cb\0\57\0\u35fa"+
    "\0\57\0\u35cb\0\u35fa\0\u3629\0\274\0\u3658\0\274\0\u3687"+
    "\0\u3687\0\57\0\274\0\u36b6\0\u36e5\0\u3714\0\57\0\274";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[432];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\3\2\1\12\1\13\1\14\1\15\1\16\1\17\1\7"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\7\1\26"+
    "\1\27\1\30\1\31\2\7\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\2\1\47\1\50\60\0\1\3\60\0\1\5"+
    "\1\51\55\0\1\7\1\0\1\7\1\52\1\0\1\53"+
    "\1\54\2\0\27\7\61\0\1\55\22\0\1\56\1\0"+
    "\1\57\1\60\1\61\1\62\1\63\2\0\1\64\1\65"+
    "\1\66\1\67\1\70\1\0\1\71\2\0\1\72\1\73"+
    "\1\74\1\75\1\76\22\0\1\7\1\0\1\7\1\52"+
    "\1\0\1\53\1\54\1\0\1\77\23\7\1\100\3\7"+
    "\17\0\1\7\1\0\1\7\1\52\1\0\1\53\1\101"+
    "\1\0\1\102\6\7\1\103\20\7\17\0\1\7\1\0"+
    "\1\7\1\52\1\0\1\53\1\54\1\0\1\104\3\7"+
    "\1\105\6\7\1\106\14\7\17\0\1\7\1\0\1\7"+
    "\1\52\1\0\1\53\1\54\1\0\1\107\6\7\1\110"+
    "\11\7\1\111\2\7\1\112\3\7\17\0\1\7\1\0"+
    "\1\7\1\52\1\0\1\53\1\54\1\0\1\113\2\7"+
    "\1\114\5\7\1\115\16\7\17\0\1\7\1\0\1\7"+
    "\1\52\1\0\1\53\1\54\1\0\1\116\7\7\1\117"+
    "\2\7\1\120\7\7\1\121\4\7\17\0\1\7\1\0"+
    "\1\7\1\52\1\0\1\53\1\54\1\0\1\122\1\7"+
    "\1\123\6\7\1\124\6\7\1\125\7\7\17\0\1\7"+
    "\1\0\1\7\1\52\1\0\1\53\1\54\1\0\1\126"+
    "\6\7\1\127\2\7\1\130\1\131\14\7\17\0\1\7"+
    "\1\0\1\7\1\52\1\0\1\53\1\54\1\0\1\132"+
    "\20\7\1\133\6\7\17\0\1\7\1\0\1\7\1\52"+
    "\1\0\1\53\1\54\1\0\1\134\6\7\1\135\20\7"+
    "\17\0\1\7\1\0\1\7\1\52\1\0\1\53\1\54"+
    "\1\0\1\71\14\7\1\136\12\7\17\0\1\7\1\0"+
    "\1\7\1\52\1\0\1\53\1\54\1\0\1\137\1\140"+
    "\17\7\1\141\1\142\1\7\1\143\3\7\17\0\1\7"+
    "\1\0\1\7\1\52\1\0\1\53\1\54\1\0\1\144"+
    "\6\7\1\145\20\7\17\0\1\7\1\0\1\7\1\52"+
    "\1\0\1\53\1\54\1\0\1\146\22\7\1\147\4\7"+
    "\17\0\1\7\1\0\1\7\1\52\1\0\1\53\1\54"+
    "\1\0\1\150\12\7\1\151\4\7\1\152\3\7\1\153"+
    "\3\7\17\0\1\7\1\0\1\7\1\52\1\0\1\53"+
    "\1\54\1\0\1\154\10\7\1\155\16\7\17\0\1\7"+
    "\1\0\1\7\1\52\1\0\1\53\1\54\1\0\1\156"+
    "\10\7\1\157\16\7\17\0\1\7\1\0\1\7\1\52"+
    "\1\0\1\53\1\54\1\0\1\160\20\7\1\161\6\7"+
    "\17\0\1\7\1\0\1\7\1\52\1\0\1\53\1\54"+
    "\1\0\1\162\20\7\1\163\6\7\14\0\1\45\1\0"+
    "\55\45\1\164\1\0\51\164\1\165\1\166\2\164\55\0"+
    "\1\47\10\0\1\167\35\0\1\170\14\0\1\171\60\0"+
    "\1\172\1\0\1\173\4\0\27\172\21\0\1\174\6\0"+
    "\27\174\26\0\1\175\47\0\1\176\66\0\1\177\1\200"+
    "\1\201\1\202\1\203\1\204\1\205\1\206\1\207\1\210"+
    "\1\211\1\212\2\0\1\213\1\0\1\214\1\215\1\216"+
    "\1\217\1\220\32\0\1\203\3\0\1\203\52\0\1\221"+
    "\23\0\1\221\32\0\1\205\5\0\1\205\50\0\1\222"+
    "\1\0\1\201\7\0\1\223\3\0\1\224\40\0\1\225"+
    "\6\0\1\226\2\0\1\227\3\0\1\230\3\0\1\216"+
    "\34\0\1\231\7\0\1\231\46\0\1\232\4\0\1\233"+
    "\2\0\1\234\2\0\1\212\2\0\1\235\40\0\1\236"+
    "\2\0\1\237\5\0\1\240\45\0\2\200\14\0\1\241"+
    "\40\0\1\242\2\0\1\243\3\0\1\244\6\0\1\245"+
    "\5\0\1\246\32\0\1\247\22\0\1\247\33\0\1\250"+
    "\4\0\1\251\15\0\1\252\33\0\1\253\6\0\1\254"+
    "\1\0\1\255\6\0\1\214\1\215\35\0\1\256\6\0"+
    "\1\254\1\0\1\255\35\0\1\7\1\0\1\7\1\52"+
    "\1\0\1\53\1\54\1\0\1\256\6\7\1\257\1\7"+
    "\1\260\16\7\17\0\1\176\6\0\1\175\57\0\1\261"+
    "\11\0\1\261\34\0\1\7\1\0\1\7\1\52\1\0"+
    "\1\53\1\54\1\0\1\261\11\7\1\262\15\7\27\0"+
    "\1\263\7\0\1\234\2\0\1\212\2\0\1\235\30\0"+
    "\1\7\1\0\1\7\1\52\1\0\1\53\1\54\1\0"+
    "\1\263\7\7\1\264\2\7\1\265\2\7\1\266\11\7"+
    "\27\0\1\267\11\0\1\270\6\0\1\215\2\0\1\246"+
    "\22\0\1\7\1\0\1\7\1\52\1\0\1\53\1\54"+
    "\1\0\1\270\11\7\1\271\15\7\17\0\1\7\1\0"+
    "\1\7\1\52\1\0\1\53\1\54\1\0\1\246\23\7"+
    "\1\272\3\7\17\0\1\7\1\0\1\7\1\52\1\0"+
    "\1\53\1\54\1\0\1\215\20\7\1\273\6\7\27\0"+
    "\1\274\5\0\1\205\3\0\1\275\34\0\1\7\1\0"+
    "\1\7\1\52\1\0\1\53\1\54\1\0\1\205\5\7"+
    "\1\276\21\7\17\0\1\7\1\0\1\7\1\52\1\0"+
    "\1\53\1\54\1\0\1\275\11\7\1\277\15\7\27\0"+
    "\1\300\4\0\1\301\15\0\1\252\23\0\1\7\1\0"+
    "\1\7\1\52\1\0\1\53\1\54\1\0\1\301\4\7"+
    "\1\302\22\7\17\0\1\7\1\0\1\7\1\52\1\0"+
    "\1\53\1\54\1\0\1\252\22\7\1\303\4\7\27\0"+
    "\1\304\1\200\10\0\1\305\3\0\1\230\5\0\1\221"+
    "\22\0\1\7\1\0\1\7\1\52\1\0\1\53\1\54"+
    "\1\0\1\221\23\7\1\306\3\7\17\0\1\7\1\0"+
    "\1\7\1\52\1\0\1\53\1\54\1\0\1\307\11\7"+
    "\1\310\3\7\1\311\11\7\17\0\1\7\1\0\1\7"+
    "\1\52\1\0\1\53\1\54\1\0\1\200\1\312\26\7"+
    "\27\0\1\313\1\0\1\201\2\0\1\314\2\0\1\231"+
    "\36\0\1\7\1\0\1\7\1\52\1\0\1\53\1\54"+
    "\1\0\1\201\1\7\1\315\25\7\17\0\1\7\1\0"+
    "\1\7\1\52\1\0\1\53\1\54\1\0\1\231\7\7"+
    "\1\316\17\7\17\0\1\7\1\0\1\7\1\52\1\0"+
    "\1\53\1\54\1\0\1\314\4\7\1\317\22\7\27\0"+
    "\1\244\6\0\1\244\37\0\1\7\1\0\1\7\1\52"+
    "\1\0\1\53\1\54\1\0\1\244\6\7\1\320\20\7"+
    "\27\0\1\224\15\0\1\224\30\0\1\7\1\0\1\7"+
    "\1\52\1\0\1\53\1\54\1\0\1\224\15\7\1\321"+
    "\11\7\17\0\1\7\1\0\1\7\1\52\1\0\1\53"+
    "\1\54\1\0\1\236\2\7\1\322\5\7\1\323\16\7"+
    "\27\0\1\324\3\0\1\203\13\0\1\214\2\0\1\247"+
    "\23\0\1\7\1\0\1\7\1\52\1\0\1\53\1\54"+
    "\1\0\1\203\3\7\1\325\23\7\17\0\1\7\1\0"+
    "\1\7\1\52\1\0\1\53\1\54\1\0\1\247\22\7"+
    "\1\326\4\7\17\0\1\7\1\0\1\7\1\52\1\0"+
    "\1\53\1\54\1\0\1\214\17\7\1\327\7\7\27\0"+
    "\1\330\11\0\1\330\34\0\1\7\1\0\1\7\1\52"+
    "\1\0\1\53\1\54\1\0\1\330\11\7\1\331\15\7"+
    "\27\0\1\251\4\0\1\251\41\0\1\7\1\0\1\7"+
    "\1\52\1\0\1\53\1\54\1\0\1\251\4\7\1\332"+
    "\22\7\27\0\1\241\15\0\1\241\30\0\1\7\1\0"+
    "\1\7\1\52\1\0\1\53\1\54\1\0\1\241\15\7"+
    "\1\333\11\7\27\0\1\226\6\0\1\226\37\0\1\7"+
    "\1\0\1\7\1\52\1\0\1\53\1\54\1\0\1\226"+
    "\6\7\1\334\20\7\27\0\1\216\21\0\1\216\24\0"+
    "\1\7\1\0\1\7\1\52\1\0\1\53\1\54\1\0"+
    "\1\216\21\7\1\335\5\7\27\0\1\245\15\0\1\245"+
    "\30\0\1\7\1\0\1\7\1\52\1\0\1\53\1\54"+
    "\1\0\1\245\15\7\1\336\11\7\27\0\1\243\2\0"+
    "\1\243\43\0\1\7\1\0\1\7\1\52\1\0\1\53"+
    "\1\54\1\0\1\243\2\7\1\337\24\7\67\0\1\164"+
    "\3\0\1\164\1\0\51\164\1\340\1\166\2\164\3\0"+
    "\1\172\1\0\1\172\6\0\27\172\21\0\1\341\6\0"+
    "\27\341\17\0\1\174\1\0\1\174\6\0\27\174\17\0"+
    "\1\176\6\0\1\342\57\0\1\343\2\0\1\344\1\345"+
    "\1\346\1\347\1\350\1\351\1\352\1\353\1\354\1\355"+
    "\1\356\1\357\1\0\1\360\1\361\2\0\1\362\32\0"+
    "\1\356\14\0\1\356\41\0\1\363\11\0\1\364\1\365"+
    "\43\0\1\366\2\0\1\366\53\0\1\367\2\0\1\370"+
    "\1\345\2\0\1\371\1\372\3\0\1\355\1\0\1\357"+
    "\40\0\1\373\4\0\1\346\5\0\1\374\43\0\1\375"+
    "\10\0\1\375\45\0\1\376\6\0\1\377\14\0\1\362"+
    "\32\0\1\u0100\7\0\1\u0101\1\u0102\1\u0103\5\0\1\360"+
    "\36\0\1\u0104\10\0\1\u0104\45\0\1\u0105\2\0\1\u0106"+
    "\15\0\1\361\35\0\1\u0107\10\0\1\u0107\45\0\1\347"+
    "\5\0\1\347\50\0\1\u0108\10\0\1\u0108\45\0\1\u0109"+
    "\10\0\1\u0109\45\0\1\u010a\2\0\1\u0106\4\0\1\u0101"+
    "\1\0\1\u0103\2\0\1\356\2\0\1\360\36\0\1\u010b"+
    "\7\0\1\u0101\1\0\1\u0103\5\0\1\360\36\0\1\u0106"+
    "\2\0\1\u0106\53\0\1\u010c\4\0\1\346\3\0\1\u0102"+
    "\45\0\1\346\4\0\1\346\51\0\1\u0102\10\0\1\u0102"+
    "\45\0\1\u010d\10\0\1\u010d\45\0\1\u010e\2\0\1\370"+
    "\1\345\3\0\1\372\1\u010f\2\0\1\355\1\0\1\357"+
    "\2\0\1\361\35\0\1\u0110\2\0\1\370\1\345\3\0"+
    "\1\372\3\0\1\355\1\0\1\357\40\0\1\u0111\10\0"+
    "\1\u0111\45\0\1\361\20\0\1\361\35\0\1\364\11\0"+
    "\1\364\11\0\1\362\32\0\1\364\11\0\1\364\44\0"+
    "\1\362\23\0\1\362\32\0\1\u0112\4\0\1\u0113\5\0"+
    "\1\365\5\0\1\u0112\35\0\1\365\12\0\1\365\43\0"+
    "\1\u0113\4\0\1\u0113\51\0\1\u0112\20\0\1\u0112\35\0"+
    "\1\u0114\10\0\1\u0114\45\0\1\u0115\6\0\1\371\1\0"+
    "\1\u0116\45\0\1\371\6\0\1\371\47\0\1\u0116\10\0"+
    "\1\u0116\45\0\1\u0117\5\0\1\347\1\377\1\0\1\u0107"+
    "\1\0\1\374\43\0\1\374\12\0\1\374\43\0\1\377"+
    "\6\0\1\377\47\0\1\u0118\6\0\1\377\3\0\1\374"+
    "\33\0\1\7\1\0\1\7\1\52\1\0\1\53\1\54"+
    "\1\0\1\374\12\7\1\u0119\14\7\17\0\1\7\1\0"+
    "\1\7\1\52\1\0\1\53\1\54\1\0\1\377\6\7"+
    "\1\u011a\20\7\27\0\1\u0103\11\0\1\u0103\34\0\1\7"+
    "\1\0\1\7\1\52\1\0\1\53\1\54\1\0\1\u0103"+
    "\11\7\1\u011b\15\7\27\0\1\u011c\10\0\1\u010f\7\0"+
    "\1\361\25\0\1\7\1\0\1\7\1\52\1\0\1\53"+
    "\1\54\1\0\1\u0111\10\7\1\u011d\16\7\17\0\1\7"+
    "\1\0\1\7\1\52\1\0\1\53\1\54\1\0\1\u0104"+
    "\10\7\1\u011e\16\7\17\0\1\7\1\0\1\7\1\52"+
    "\1\0\1\53\1\54\1\0\1\361\20\7\1\u011f\6\7"+
    "\27\0\1\u0120\5\0\1\347\1\0\1\u0101\46\0\1\u0101"+
    "\7\0\1\u0101\36\0\1\7\1\0\1\7\1\52\1\0"+
    "\1\53\1\54\1\0\1\u0101\7\7\1\u0121\17\7\17\0"+
    "\1\7\1\0\1\7\1\52\1\0\1\53\1\54\1\0"+
    "\1\347\5\7\1\u0122\21\7\27\0\1\u0123\10\0\1\u0123"+
    "\35\0\1\7\1\0\1\7\1\52\1\0\1\53\1\54"+
    "\1\0\1\u0123\10\7\1\u0124\16\7\17\0\1\7\1\0"+
    "\1\7\1\52\1\0\1\53\1\54\1\0\1\u0116\10\7"+
    "\1\u0125\16\7\27\0\1\u0126\10\0\1\u0126\45\0\1\u0127"+
    "\10\0\1\u0127\35\0\1\7\1\0\1\7\1\52\1\0"+
    "\1\53\1\54\1\0\1\u0109\10\7\1\u0128\16\7\17\0"+
    "\1\7\1\0\1\7\1\52\1\0\1\53\1\54\1\0"+
    "\1\u0127\10\7\1\u0129\16\7\27\0\1\u012a\2\0\1\370"+
    "\1\345\3\0\1\372\1\u010d\2\0\1\355\1\356\1\357"+
    "\30\0\1\7\1\0\1\7\1\52\1\0\1\53\1\54"+
    "\1\0\1\356\14\7\1\u012b\12\7\17\0\1\7\1\0"+
    "\1\7\1\52\1\0\1\53\1\54\1\0\1\u010d\10\7"+
    "\1\u012c\16\7\17\0\1\7\1\0\1\7\1\52\1\0"+
    "\1\53\1\54\1\0\1\u0110\2\7\1\u012d\1\u012e\3\7"+
    "\1\u012f\3\7\1\u0130\1\7\1\u0131\11\7\17\0\1\7"+
    "\1\0\1\7\1\52\1\0\1\53\1\54\1\0\1\u0113"+
    "\4\7\1\u0132\22\7\17\0\1\7\1\0\1\7\1\52"+
    "\1\0\1\53\1\54\1\0\1\u0106\2\7\1\u0133\24\7"+
    "\17\0\1\7\1\0\1\7\1\52\1\0\1\53\1\54"+
    "\1\0\1\364\11\7\1\u0134\15\7\17\0\1\7\1\0"+
    "\1\7\1\52\1\0\1\53\1\54\1\0\1\362\23\7"+
    "\1\u0135\3\7\27\0\1\u0136\2\0\1\366\5\0\1\u0114"+
    "\35\0\1\7\1\0\1\7\1\52\1\0\1\53\1\54"+
    "\1\0\1\366\2\7\1\u0137\24\7\17\0\1\7\1\0"+
    "\1\7\1\52\1\0\1\53\1\54\1\0\1\u0114\10\7"+
    "\1\u0138\16\7\17\0\1\7\1\0\1\7\1\52\1\0"+
    "\1\53\1\54\1\0\1\u0107\10\7\1\u0139\16\7\27\0"+
    "\1\360\17\0\1\360\26\0\1\7\1\0\1\7\1\52"+
    "\1\0\1\53\1\54\1\0\1\360\17\7\1\u013a\7\7"+
    "\17\0\1\7\1\0\1\7\1\52\1\0\1\53\1\54"+
    "\1\0\1\371\6\7\1\u013b\20\7\17\0\1\7\1\0"+
    "\1\7\1\52\1\0\1\53\1\54\1\0\1\346\4\7"+
    "\1\u013c\22\7\17\0\1\7\1\0\1\7\1\52\1\0"+
    "\1\53\1\54\1\0\1\u0112\20\7\1\u013d\6\7\17\0"+
    "\1\7\1\0\1\7\1\52\1\0\1\53\1\54\1\0"+
    "\1\365\12\7\1\u013e\14\7\17\0\1\341\1\0\1\341"+
    "\6\0\27\341\27\0\1\u013f\1\0\1\u0140\1\0\1\u0141"+
    "\4\0\1\u0142\1\0\1\u0143\1\0\1\u0144\1\u0145\1\u0146"+
    "\1\u0147\1\u0148\1\u0149\1\0\1\u014a\1\u014b\31\0\1\u014c"+
    "\3\0\1\u0141\12\0\1\u0146\4\0\1\u014d\32\0\1\u0148"+
    "\20\0\1\u0148\35\0\1\u014e\15\0\1\u014f\6\0\1\u014b"+
    "\31\0\1\u0150\10\0\1\u0151\6\0\1\u0147\36\0\1\u0152"+
    "\1\0\1\u0153\6\0\1\u0154\1\0\1\u0143\2\0\1\u0145"+
    "\5\0\1\u0155\32\0\1\u0156\10\0\1\u0156\45\0\1\u0157"+
    "\1\0\1\u0157\54\0\1\u0144\14\0\1\u0144\41\0\1\u0149"+
    "\21\0\1\u0149\34\0\1\u0158\10\0\1\u0158\45\0\1\u0159"+
    "\10\0\1\u0159\45\0\1\u014d\23\0\1\u014d\32\0\1\u015a"+
    "\3\0\1\u0141\10\0\1\u0144\1\u014f\1\0\1\u0147\1\u0148"+
    "\1\u0149\34\0\1\u0141\3\0\1\u0141\52\0\1\u014f\15\0"+
    "\1\u014f\40\0\1\u0147\17\0\1\u0147\36\0\1\u015b\23\0"+
    "\1\u015b\32\0\1\u014b\10\0\1\u0159\13\0\1\u014b\31\0"+
    "\1\u014b\24\0\1\u014b\31\0\1\u015c\1\0\1\u0153\6\0"+
    "\1\u015d\4\0\1\u0145\40\0\1\u0151\10\0\1\u0151\45\0"+
    "\1\u015e\1\0\1\u0153\13\0\1\u0145\40\0\1\u015f\23\0"+
    "\1\u015f\32\0\1\u0146\16\0\1\u0146\37\0\1\u0143\12\0"+
    "\1\u0143\43\0\1\u0154\10\0\1\u0154\45\0\1\u0160\10\0"+
    "\1\u015d\5\0\1\u0146\37\0\1\u015d\10\0\1\u015d\45\0"+
    "\1\u0161\3\0\1\u0141\10\0\1\u0144\2\0\1\u0147\1\u0148"+
    "\1\u0149\1\0\1\u0155\32\0\1\u0155\23\0\1\u0155\32\0"+
    "\1\u0162\3\0\1\u0141\10\0\1\u0144\2\0\1\u0147\1\u0148"+
    "\1\u0149\34\0\1\u0163\12\0\1\u0143\2\0\1\u014f\40\0"+
    "\1\u0164\1\0\1\u0157\22\0\1\u014b\21\0\1\7\1\0"+
    "\1\7\1\52\1\0\1\53\1\54\1\0\1\u0157\1\7"+
    "\1\u0165\25\7\17\0\1\7\1\0\1\7\1\52\1\0"+
    "\1\53\1\54\1\0\1\u014b\24\7\1\u0166\2\7\17\0"+
    "\1\7\1\0\1\7\1\52\1\0\1\53\1\54\1\0"+
    "\1\u015b\23\7\1\u0167\3\7\17\0\1\7\1\0\1\7"+
    "\1\52\1\0\1\53\1\54\1\0\1\u015f\23\7\1\u0168"+
    "\3\7\17\0\1\7\1\0\1\7\1\52\1\0\1\53"+
    "\1\54\1\0\1\u0151\10\7\1\u0169\16\7\27\0\1\u0145"+
    "\15\0\1\u0145\30\0\1\7\1\0\1\7\1\52\1\0"+
    "\1\53\1\54\1\0\1\u0145\15\7\1\u016a\11\7\17\0"+
    "\1\7\1\0\1\7\1\52\1\0\1\53\1\54\1\0"+
    "\1\u0143\12\7\1\u016b\14\7\27\0\1\u016c\1\0\1\u0153"+
    "\6\0\1\u0154\45\0\1\u0153\1\0\1\u0153\44\0\1\7"+
    "\1\0\1\7\1\52\1\0\1\53\1\54\1\0\1\u0154"+
    "\10\7\1\u016d\16\7\17\0\1\7\1\0\1\7\1\52"+
    "\1\0\1\53\1\54\1\0\1\u0153\1\7\1\u016e\25\7"+
    "\17\0\1\7\1\0\1\7\1\52\1\0\1\53\1\54"+
    "\1\0\1\u0141\3\7\1\u016f\23\7\17\0\1\7\1\0"+
    "\1\7\1\52\1\0\1\53\1\54\1\0\1\u0148\20\7"+
    "\1\u0170\6\7\17\0\1\7\1\0\1\7\1\52\1\0"+
    "\1\53\1\54\1\0\1\u0147\17\7\1\u0171\7\7\17\0"+
    "\1\7\1\0\1\7\1\52\1\0\1\53\1\54\1\0"+
    "\1\u0144\14\7\1\u0172\12\7\17\0\1\7\1\0\1\7"+
    "\1\52\1\0\1\53\1\54\1\0\1\u0149\21\7\1\u0173"+
    "\5\7\17\0\1\7\1\0\1\7\1\52\1\0\1\53"+
    "\1\54\1\0\1\u0146\16\7\1\u0174\10\7\17\0\1\7"+
    "\1\0\1\7\1\52\1\0\1\53\1\54\1\0\1\u0156"+
    "\10\7\1\u0175\16\7\17\0\1\7\1\0\1\7\1\52"+
    "\1\0\1\53\1\54\1\0\1\u0159\10\7\1\u0176\16\7"+
    "\17\0\1\7\1\0\1\7\1\52\1\0\1\53\1\54"+
    "\1\0\1\u014d\23\7\1\u0177\3\7\17\0\1\7\1\0"+
    "\1\7\1\52\1\0\1\53\1\54\1\0\1\u0158\10\7"+
    "\1\u0178\16\7\17\0\1\7\1\0\1\7\1\52\1\0"+
    "\1\53\1\54\1\0\1\u014f\15\7\1\u0179\11\7\27\0"+
    "\1\u017a\1\u017b\1\0\1\u017c\1\0\1\u017d\2\0\1\u017e"+
    "\1\u017f\1\0\1\u0180\1\0\1\u0181\1\u0182\4\0\1\u0183"+
    "\1\u0184\32\0\1\u0181\14\0\1\u0181\1\u0182\40\0\1\u0180"+
    "\7\0\1\u0185\2\0\1\u0180\43\0\1\u017d\4\0\1\u017d"+
    "\51\0\1\u017c\2\0\1\u017c\53\0\1\u0186\10\0\1\u0186"+
    "\45\0\1\u0187\10\0\1\u0187\45\0\2\u017b\55\0\1\u0184"+
    "\23\0\1\u0184\32\0\1\u0183\22\0\1\u0183\33\0\1\u0188"+
    "\7\0\1\u0189\5\0\1\u018a\40\0\1\u018b\7\0\1\u0189"+
    "\1\u0187\45\0\1\u0189\7\0\1\u0189\46\0\1\u018c\10\0"+
    "\1\u018c\45\0\1\u0180\4\0\1\u017d\3\0\1\u0186\1\0"+
    "\1\u0180\2\0\1\u0182\40\0\1\u0182\15\0\1\u0182\40\0"+
    "\1\u0180\12\0\1\u0180\43\0\1\u018a\15\0\1\u018a\40\0"+
    "\1\u0181\14\0\1\u0181\41\0\1\u0185\7\0\1\u0185\46\0"+
    "\1\u018d\1\u017b\1\0\1\u017c\5\0\1\u018c\11\0\1\u0183"+
    "\1\u0184\32\0\1\u0186\7\0\1\u0185\1\u0186\4\0\1\u0182"+
    "\40\0\1\u0186\10\0\1\u0186\4\0\1\u0182\40\0\1\u018e"+
    "\7\0\1\u0185\1\u0187\45\0\1\u018d\1\u017b\1\0\1\u017c"+
    "\12\0\1\u018a\4\0\1\u0183\1\u0184\32\0\1\u018d\1\u017b"+
    "\1\0\1\u017c\17\0\1\u0183\1\u0184\32\0\1\u017d\4\0"+
    "\1\u017d\3\0\1\u018c\35\0\1\7\1\0\1\7\1\52"+
    "\1\0\1\53\1\54\1\0\1\u0181\14\7\1\u018f\12\7"+
    "\17\0\1\7\1\0\1\7\1\52\1\0\1\53\1\54"+
    "\1\0\1\u018a\15\7\1\u0190\11\7\17\0\1\7\1\0"+
    "\1\7\1\52\1\0\1\53\1\54\1\0\1\u0186\10\7"+
    "\1\u0191\16\7\17\0\1\7\1\0\1\7\1\52\1\0"+
    "\1\53\1\54\1\0\1\u017d\4\7\1\u0192\22\7\27\0"+
    "\1\u0180\12\0\1\u0180\2\0\1\u0182\30\0\1\7\1\0"+
    "\1\7\1\52\1\0\1\53\1\54\1\0\1\u0180\12\7"+
    "\1\u0193\14\7\17\0\1\7\1\0\1\7\1\52\1\0"+
    "\1\53\1\54\1\0\1\u0182\15\7\1\u0194\11\7\17\0"+
    "\1\7\1\0\1\7\1\52\1\0\1\53\1\54\1\0"+
    "\1\u0184\23\7\1\u0195\3\7\17\0\1\7\1\0\1\7"+
    "\1\52\1\0\1\53\1\54\1\0\1\u017b\1\u0196\26\7"+
    "\17\0\1\7\1\0\1\7\1\52\1\0\1\53\1\54"+
    "\1\0\1\u017c\2\7\1\u0197\24\7\17\0\1\7\1\0"+
    "\1\7\1\52\1\0\1\53\1\54\1\0\1\u0183\22\7"+
    "\1\u0198\4\7\17\0\1\7\1\0\1\7\1\52\1\0"+
    "\1\53\1\54\1\0\1\u0187\10\7\1\u0199\16\7\17\0"+
    "\1\7\1\0\1\7\1\52\1\0\1\53\1\54\1\0"+
    "\1\u0189\7\7\1\u019a\17\7\17\0\1\7\1\0\1\7"+
    "\1\52\1\0\1\53\1\54\1\0\1\u0185\7\7\1\u019b"+
    "\17\7\17\0\1\7\1\0\1\7\1\52\1\0\1\53"+
    "\1\54\1\0\1\u018c\10\7\1\u019c\16\7\27\0\1\u019d"+
    "\1\0\1\u019e\6\0\1\u019f\1\u01a0\3\0\1\u01a1\40\0"+
    "\1\u01a0\11\0\1\u01a0\44\0\1\u01a1\15\0\1\u01a1\40\0"+
    "\1\u019e\1\0\1\u019e\54\0\1\u019f\10\0\1\u019f\45\0"+
    "\1\u01a2\1\0\1\u019e\13\0\1\u01a1\40\0\1\u01a3\10\0"+
    "\1\u019f\1\u01a0\34\0\1\7\1\0\1\7\1\52\1\0"+
    "\1\53\1\54\1\0\1\u01a0\11\7\1\u01a4\15\7\17\0"+
    "\1\7\1\0\1\7\1\52\1\0\1\53\1\54\1\0"+
    "\1\u019f\10\7\1\u01a5\16\7\17\0\1\7\1\0\1\7"+
    "\1\52\1\0\1\53\1\54\1\0\1\u019e\1\7\1\u01a6"+
    "\25\7\17\0\1\7\1\0\1\7\1\52\1\0\1\53"+
    "\1\54\1\0\1\u01a1\15\7\1\u01a7\11\7\27\0\1\u01a8"+
    "\6\0\1\u01a9\1\0\1\u01aa\45\0\1\u01a9\6\0\1\u01a9"+
    "\47\0\1\u01aa\10\0\1\u01aa\35\0\1\7\1\0\1\7"+
    "\1\52\1\0\1\53\1\54\1\0\1\u01aa\10\7\1\u01ab"+
    "\16\7\17\0\1\7\1\0\1\7\1\52\1\0\1\53"+
    "\1\54\1\0\1\u01a9\6\7\1\u01ac\20\7\27\0\1\u01ad"+
    "\11\0\1\u01ad\34\0\1\7\1\0\1\7\1\52\1\0"+
    "\1\53\1\54\1\0\1\u01ad\11\7\1\u01ae\15\7\27\0"+
    "\1\u01af\11\0\1\u01af\34\0\1\7\1\0\1\7\1\52"+
    "\1\0\1\53\1\54\1\0\1\u01af\11\7\1\u01b0\15\7"+
    "\14\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[14147];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\2\1\1\11\1\1\1\11\25\1\7\11"+
    "\4\1\4\0\1\11\1\0\1\1\3\0\1\11\1\0"+
    "\1\11\2\0\1\1\2\0\1\1\2\0\1\1\1\0"+
    "\1\1\2\0\4\1\1\0\3\1\1\0\6\1\1\0"+
    "\3\1\1\0\3\1\1\0\1\1\1\0\7\1\1\0"+
    "\1\1\1\0\5\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\2\11\2\1"+
    "\1\0\1\1\1\11\1\0\1\1\1\11\3\0\1\1"+
    "\1\11\5\0\1\1\2\0\1\11\1\0\1\1\4\0"+
    "\1\1\2\0\1\11\1\0\2\1\5\0\1\11\1\1"+
    "\3\0\1\11\10\0\2\1\1\0\1\1\1\0\4\1"+
    "\1\0\4\1\1\0\3\1\1\11\3\1\1\0\5\1"+
    "\2\0\7\1\1\0\3\1\1\0\11\1\1\11\1\1"+
    "\2\0\2\11\2\0\3\1\1\0\1\11\2\0\1\11"+
    "\1\0\1\1\1\0\1\11\5\0\1\1\1\0\1\1"+
    "\2\0\1\1\2\0\1\11\1\0\1\1\1\0\1\11"+
    "\1\1\1\0\3\1\1\11\1\1\3\0\3\11\2\0"+
    "\1\1\1\0\12\1\1\0\2\1\2\0\30\1\1\0"+
    "\1\11\1\1\7\0\1\1\1\11\1\1\1\0\1\1"+
    "\1\0\1\1\1\11\1\1\2\0\1\1\1\11\2\0"+
    "\1\11\1\1\1\0\2\1\1\0\1\11\3\1\1\0"+
    "\10\1\1\0\16\1\1\11\1\0\1\11\2\1\3\11"+
    "\1\0\3\11\1\0\1\1\1\0\1\11\1\0\1\11"+
    "\21\1\1\0\1\11\1\0\1\11\7\1\1\0\1\11"+
    "\2\1\1\0\1\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[432];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;
  
  public int getTextPosition(){
	  return(zzCurrentPos);
  }

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  private AParserAll yyparser;

  public AYylex_Old(java.io.Reader r, AParserAll yyparser) {
    this(r);
    this.yyparser = yyparser;
    this.yyline = 0;
  }
  public AYylex_Old(String s, AParserAll yyparser) {
    this(s);
    this.yyparser = yyparser;
    this.yyline = 0;
  }
  AYylex_Old(String s) {
    this(new StringReader(s)); 
  }
  private void lg(String s){
    System.out.println(s);
  }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  AYylex_Old(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  AYylex_Old(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 172) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 45: 
          { lg("Else");return AParserAll.ELSE;
          }
        case 76: break;
        case 51: 
          { lg("INTO");return AParserAll.INTO;
          }
        case 77: break;
        case 32: 
          { return AParserAll.LTE;
          }
        case 78: break;
        case 69: 
          { return AParserAll.ENDFOR;
          }
        case 79: break;
        case 55: 
          { return AParserAll.LOAD;
          }
        case 80: break;
        case 1: 
          { lg("Token não identificado ["+yytext()+"]");
          }
        case 81: break;
        case 67: 
          { return AParserAll.BRANCH;
          }
        case 82: break;
        case 39: 
          { return AParserAll.AND;
          }
        case 83: break;
        case 49: 
          { lg("JOI");return AParserAll.JOIN;
          }
        case 84: break;
        case 7: 
          { lg(">");return AParserAll.GT;
          }
        case 85: break;
        case 19: 
          { lg("ponto");return AParserAll.POINT;
          }
        case 86: break;
        case 26: 
          { lg("As");return AParserAll.AS;
          }
        case 87: break;
        case 63: 
          { return AParserAll.APPEND;
          }
        case 88: break;
        case 61: 
          { return AParserAll.WHERE;
          }
        case 89: break;
        case 56: 
          { lg("Endif");return AParserAll.ENDIF;
          }
        case 90: break;
        case 16: 
          { return AParserAll.PLUS;
          }
        case 91: break;
        case 35: 
          { lg(yytext());yyparser.yylval = new ParserVal(yytext());return AParserAll.NAMESQLJ;
          }
        case 92: break;
        case 74: 
          { return AParserAll.ENDWHILE;
          }
        case 93: break;
        case 3: 
          { yyparser.yylval = new ParserVal(new Variant(Integer.parseInt(yytext()))); return AParserAll.NUMINT;
          }
        case 94: break;
        case 53: 
          { return AParserAll.TYPE;
          }
        case 95: break;
        case 11: 
          { lg(yytext());yyparser.yylval = new ParserVal(yytext());return AParserAll.TYPEF;
          }
        case 96: break;
        case 66: 
          { return AParserAll.SCREEN;
          }
        case 97: break;
        case 41: 
          { return AParserAll.KEY;
          }
        case 98: break;
        case 44: 
          { lg(yytext());yyparser.yylval = new ParserVal(yytext());return AParserAll.CALLPROG;
          }
        case 99: break;
        case 6: 
          { return AParserAll.MINUS;
          }
        case 100: break;
        case 5: 
          { lg(yytext());yyparser.yylval = new ParserVal(yytext());return AParserAll.NAME;
          }
        case 101: break;
        case 47: 
          { lg("FRM");return AParserAll.FROM;
          }
        case 102: break;
        case 28: 
          { return AParserAll.TO;
          }
        case 103: break;
        case 50: 
          { return AParserAll.EACH;
          }
        case 104: break;
        case 65: 
          { return AParserAll.DELETE;
          }
        case 105: break;
        case 36: 
          { lg(yytext());yyparser.yylval = new ParserVal(yytext());return AParserAll.TABLE;
          }
        case 106: break;
        case 64: 
          { lg("VAL");return AParserAll.VALUES;
          }
        case 107: break;
        case 17: 
          { return AParserAll.DIV;
          }
        case 108: break;
        case 73: 
          { return AParserAll.TBFIRST;
          }
        case 109: break;
        case 15: 
          { return AParserAll.EQ;
          }
        case 110: break;
        case 59: 
          { return AParserAll.BREAK;
          }
        case 111: break;
        case 12: 
          { lg(yytext());yyparser.yylval = new ParserVal(yytext());return AParserAll.TYPED;
          }
        case 112: break;
        case 29: 
          { lg("ON");return AParserAll.ON;
          }
        case 113: break;
        case 58: 
          { lg("INN");return AParserAll.INNER;
          }
        case 114: break;
        case 33: 
          { lg("FLOAT: "+yytext());yyparser.yylval = new ParserVal(new Variant(Float.parseFloat(yytext().replace(',','.')))); return AParserAll.NUMFLT;
          }
        case 115: break;
        case 37: 
          { lg("Dim");return AParserAll.DIM;
          }
        case 116: break;
        case 72: 
          { return AParserAll.ENDTYPE;
          }
        case 117: break;
        case 31: 
          { return AParserAll.NEQ;
          }
        case 118: break;
        case 54: 
          { return AParserAll.GOTO;
          }
        case 119: break;
        case 71: 
          { lg("upd");return AParserAll.UPDATE;
          }
        case 120: break;
        case 40: 
          { return AParserAll.OUT;
          }
        case 121: break;
        case 20: 
          { lg("Comentário:"+yytext());return AParserAll.COMMENT;
          }
        case 122: break;
        case 46: 
          { return AParserAll.READ;
          }
        case 123: break;
        case 38: 
          { return AParserAll.SUB;
          }
        case 124: break;
        case 14: 
          { return AParserAll.RPAR;
          }
        case 125: break;
        case 4: 
          { return AParserAll.COMMA;
          }
        case 126: break;
        case 9: 
          { lg(yytext());yyparser.yylval = new ParserVal(yytext());return AParserAll.TYPEC;
          }
        case 127: break;
        case 10: 
          { lg(yytext());yyparser.yylval = new ParserVal(yytext());return AParserAll.TYPEI;
          }
        case 128: break;
        case 22: 
          { return AParserAll.LT;
          }
        case 129: break;
        case 70: 
          { lg("INS");return AParserAll.INSERT;
          }
        case 130: break;
        case 48: 
          { return AParserAll.CALL;
          }
        case 131: break;
        case 68: 
          { lg("SEL");return AParserAll.SELECT;
          }
        case 132: break;
        case 25: 
          { lg("If");return AParserAll.IF;
          }
        case 133: break;
        case 30: 
          { lg("String:"+yytext());yyparser.yylval = new ParserVal(new Variant(yytext().replaceAll("\"","")));
            return AParserAll.STRING;
          }
        case 134: break;
        case 62: 
          { return AParserAll.ENDSUB;
          }
        case 135: break;
        case 27: 
          { return AParserAll.IN;
          }
        case 136: break;
        case 13: 
          { return AParserAll.LPAR;
          }
        case 137: break;
        case 18: 
          { return AParserAll.TIMES;
          }
        case 138: break;
        case 52: 
          { return AParserAll.TRUE;
          }
        case 139: break;
        case 34: 
          { lg(yytext());yyparser.yylval = new ParserVal(yytext());return AParserAll.FIELD;
          }
        case 140: break;
        case 8: 
          { lg(yytext());yyparser.yylval = new ParserVal(yytext());return AParserAll.TYPEB;
          }
        case 141: break;
        case 23: 
          { return AParserAll.GTE;
          }
        case 142: break;
        case 42: 
          { return AParserAll.FOR;
          }
        case 143: break;
        case 75: 
          { return AParserAll.NATIVECALL;
          }
        case 144: break;
        case 60: 
          { return AParserAll.FALSE;
          }
        case 145: break;
        case 2: 
          { yyline++;lg("ENTER");return AParserAll.NL;
          }
        case 146: break;
        case 24: 
          { return AParserAll.OR;
          }
        case 147: break;
        case 21: 
          { 
          }
        case 148: break;
        case 57: 
          { lg("While");return AParserAll.WHILE;
          }
        case 149: break;
        case 43: 
          { lg("SET");return AParserAll.SET;
          }
        case 150: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return 0; }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
