package com.jsv.editor;
/* The following code was generated by JFlex 1.4.3 on 14/08/12 20:49 */

import java.io.StringReader;
import com.jsv.data.Variant;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 14/08/12 20:49 from the specification file
 * <tt>C:/Renato/Pessoal/Projetos/RenR3/Ling/scanner.flex</tt>
 */
class BYylex {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\55\1\1\2\0\1\2\22\0\1\55\1\0\1\53\4\0"+
    "\1\52\1\43\1\44\1\50\1\46\1\4\1\6\1\51\1\47\12\3"+
    "\2\0\1\56\1\45\1\7\2\0\1\22\1\14\1\15\1\20\1\24"+
    "\1\17\1\41\1\30\1\16\1\42\1\40\1\25\1\21\1\26\1\34"+
    "\1\36\1\5\1\37\1\23\1\31\1\33\1\32\1\27\1\5\1\35"+
    "\1\5\1\11\1\54\1\12\3\0\1\22\1\14\1\15\1\20\1\24"+
    "\1\17\1\41\1\30\1\16\1\42\1\40\1\25\1\21\1\26\1\34"+
    "\1\36\1\5\1\37\1\23\1\31\1\33\1\32\1\27\1\5\1\35"+
    "\1\5\1\0\1\13\1\0\1\10\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\4\1\5\1\6\1\7"+
    "\2\10\1\11\1\12\1\13\1\14\17\5\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\1\1\25"+
    "\1\26\4\0\1\27\1\0\1\30\3\0\1\31\1\0"+
    "\1\32\2\0\1\33\2\0\1\34\2\0\1\30\1\0"+
    "\1\5\2\0\1\5\2\31\1\33\1\0\3\5\1\0"+
    "\2\5\1\0\1\5\2\32\2\5\1\0\3\5\1\0"+
    "\3\5\1\0\1\5\1\0\2\5\1\34\1\5\1\34"+
    "\2\5\1\0\1\5\1\0\1\5\1\30\1\35\1\5"+
    "\1\30\1\0\1\5\1\0\1\5\1\0\1\5\1\0"+
    "\1\5\1\0\1\36\1\0\1\37\1\40\1\41\1\42"+
    "\1\0\1\43\1\44\1\0\1\45\1\46\3\0\1\47"+
    "\1\45\5\0\1\50\2\0\1\51\1\0\1\52\4\0"+
    "\1\53\2\0\1\53\1\0\2\47\5\0\1\50\1\52"+
    "\4\0\1\52\10\0\2\5\1\0\1\5\1\0\3\5"+
    "\1\52\1\0\1\5\1\52\1\5\1\45\1\0\1\45"+
    "\2\5\3\47\1\5\1\46\1\0\1\5\1\53\1\5"+
    "\1\53\1\46\2\0\7\5\1\0\3\5\1\0\2\5"+
    "\1\50\1\5\1\51\2\5\1\36\1\54\1\11\1\55"+
    "\2\0\1\56\1\57\2\0\1\55\1\60\1\61\1\0"+
    "\1\62\2\0\1\63\1\0\1\61\1\0\1\61\5\0"+
    "\1\56\1\0\1\55\2\0\1\60\2\0\1\60\1\0"+
    "\1\63\1\0\1\64\1\65\1\0\2\60\1\56\1\55"+
    "\1\63\4\0\1\66\1\0\1\67\1\66\1\65\2\0"+
    "\1\57\1\0\2\5\1\60\1\63\2\5\1\63\1\57"+
    "\1\5\1\57\1\0\3\5\2\0\2\5\1\55\1\62"+
    "\1\55\5\5\1\67\3\5\1\65\1\5\1\65\1\64"+
    "\2\5\1\56\1\66\1\61\1\70\1\0\1\70\1\71"+
    "\7\0\1\72\1\73\1\70\1\0\1\73\1\0\2\74"+
    "\1\72\2\0\1\72\1\71\2\0\1\75\1\70\1\0"+
    "\2\74\1\0\1\72\1\74\3\70\2\0\1\73\1\5"+
    "\1\73\1\5\1\72\1\74\3\5\1\0\2\5\1\70"+
    "\5\5\1\71\1\75\3\5\2\76\1\0\1\77\1\100"+
    "\1\101\1\102\1\103\1\104\1\105\1\0\1\106\1\100"+
    "\1\101\1\0\1\107\1\0\1\107\1\105\1\110\1\76"+
    "\1\100\1\103\1\107\1\101\1\105\1\77\1\102\1\104"+
    "\1\106\1\76\4\5\1\100\1\110\1\111\1\0\1\111"+
    "\1\0\2\112\1\111\1\5\1\111\1\5\1\112\1\113"+
    "\1\0\2\113\1\5\1\0\1\5\2\114";

  private static int [] zzUnpackAction() {
    int [] result = new int[446];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\57\0\136\0\215\0\57\0\274\0\57"+
    "\0\353\0\u011a\0\u0149\0\u0178\0\u01a7\0\u01d6\0\u0205\0\u0234"+
    "\0\u0263\0\u0292\0\u02c1\0\u02f0\0\u031f\0\u034e\0\u037d\0\u03ac"+
    "\0\u03db\0\u040a\0\u0439\0\u0468\0\u0497\0\u04c6\0\57\0\57"+
    "\0\57\0\57\0\57\0\57\0\57\0\u04f5\0\u0524\0\u0553"+
    "\0\u0582\0\u05b1\0\u05e0\0\u060f\0\u063e\0\57\0\u066d\0\u069c"+
    "\0\u06cb\0\u06fa\0\u0729\0\57\0\u0758\0\57\0\u0787\0\u07b6"+
    "\0\u07e5\0\u0814\0\u0843\0\u0872\0\u08a1\0\u08d0\0\u08ff\0\u092e"+
    "\0\u095d\0\u098c\0\u09bb\0\u09ea\0\u0a19\0\274\0\u0a48\0\u0a77"+
    "\0\u0aa6\0\u0ad5\0\u0b04\0\u0b33\0\u0b62\0\u0b91\0\u0bc0\0\u0bef"+
    "\0\u0c1e\0\274\0\u0c4d\0\u0c7c\0\u0cab\0\u0cda\0\u0d09\0\u0d38"+
    "\0\u0d67\0\u0d96\0\u0dc5\0\u0df4\0\u0e23\0\u0e52\0\u0e81\0\u0eb0"+
    "\0\u0edf\0\u0f0e\0\u0f3d\0\274\0\u0f6c\0\u0f9b\0\u0fca\0\u0ff9"+
    "\0\u1028\0\u1057\0\u1086\0\274\0\u10b5\0\274\0\u10e4\0\u1113"+
    "\0\u1142\0\u1171\0\u11a0\0\u11cf\0\u11fe\0\u122d\0\u0524\0\u125c"+
    "\0\u128b\0\57\0\57\0\u05b1\0\u12ba\0\u12e9\0\u1318\0\57"+
    "\0\u1347\0\u1376\0\57\0\u13a5\0\u13d4\0\u1403\0\u1432\0\57"+
    "\0\u1461\0\u1490\0\u14bf\0\u14ee\0\u151d\0\u154c\0\u157b\0\u15aa"+
    "\0\57\0\u15d9\0\u1608\0\u1608\0\u1637\0\u1666\0\u1695\0\u16c4"+
    "\0\u16f3\0\u1722\0\57\0\u1751\0\u1780\0\u17af\0\u17de\0\u180d"+
    "\0\u183c\0\u186b\0\u189a\0\57\0\u18c9\0\u18f8\0\u1927\0\u1956"+
    "\0\u1985\0\57\0\u19b4\0\u19e3\0\u1a12\0\u1a41\0\u1a70\0\u1a9f"+
    "\0\u1ace\0\u1afd\0\u1b2c\0\u1b5b\0\u1b8a\0\u1bb9\0\u1be8\0\u1c17"+
    "\0\u1c46\0\u1c75\0\u1ca4\0\u1cd3\0\u1d02\0\274\0\u1d31\0\u1d60"+
    "\0\u1d60\0\274\0\u1d8f\0\u1dbe\0\u1a41\0\57\0\274\0\u1ded"+
    "\0\u1e1c\0\u1e4b\0\u1e7a\0\u1e4b\0\u1ea9\0\274\0\274\0\u1ed8"+
    "\0\u17af\0\u1f07\0\u1f36\0\u1f65\0\u1f94\0\u1fc3\0\u1ff2\0\u2021"+
    "\0\u2050\0\u207f\0\u20ae\0\u20dd\0\u210c\0\u213b\0\u216a\0\274"+
    "\0\u2199\0\274\0\u21c8\0\u21f7\0\u128b\0\u2226\0\57\0\u2255"+
    "\0\u2284\0\u22b3\0\57\0\57\0\u22e2\0\u2311\0\u2340\0\u236f"+
    "\0\u239e\0\u23cd\0\57\0\u23fc\0\u242b\0\57\0\u245a\0\u236f"+
    "\0\u236f\0\57\0\u2489\0\u24b8\0\u24e7\0\u2516\0\u2545\0\u239e"+
    "\0\u239e\0\u2574\0\u25a3\0\u25d2\0\u2601\0\u2630\0\u265f\0\57"+
    "\0\u268e\0\u26bd\0\u26bd\0\57\0\u26ec\0\u271b\0\u274a\0\u2779"+
    "\0\u265f\0\57\0\u27a8\0\u27d7\0\u2806\0\u2835\0\u2574\0\u2864"+
    "\0\u2864\0\57\0\57\0\57\0\u2893\0\u26ec\0\u28c2\0\u28c2"+
    "\0\u28f1\0\u2920\0\274\0\u2806\0\u294f\0\u297e\0\274\0\u2630"+
    "\0\u29ad\0\274\0\u29dc\0\u2a0b\0\u2a3a\0\u2a69\0\u2a98\0\u2ac7"+
    "\0\u2af6\0\u2b25\0\u2835\0\274\0\274\0\u2b54\0\u2b83\0\u2bb2"+
    "\0\u2be1\0\u2c10\0\274\0\u2c3f\0\u2c6e\0\u2c9d\0\u2489\0\u2ccc"+
    "\0\274\0\274\0\u2cfb\0\u2d2a\0\274\0\274\0\274\0\u2d59"+
    "\0\u2d88\0\u2db7\0\u2de6\0\u2e15\0\u2e44\0\u2e73\0\u2ea2\0\u2ed1"+
    "\0\u2f00\0\u2f2f\0\u2f5e\0\57\0\u2f8d\0\u2fbc\0\u2feb\0\u2feb"+
    "\0\u2ed1\0\57\0\u301a\0\u3049\0\u3078\0\u30a7\0\57\0\u30d6"+
    "\0\u3105\0\57\0\u3134\0\u30a7\0\u3163\0\u3105\0\u3192\0\57"+
    "\0\u31c1\0\u31f0\0\57\0\u321f\0\u2db7\0\u324e\0\u30d6\0\u327d"+
    "\0\274\0\u32ac\0\274\0\274\0\u32db\0\u330a\0\u3339\0\u3368"+
    "\0\u3397\0\u33c6\0\274\0\u33f5\0\u3424\0\u3453\0\u3482\0\u34b1"+
    "\0\274\0\274\0\u34e0\0\u350f\0\u353e\0\u356d\0\57\0\u359c"+
    "\0\57\0\u35cb\0\u35fa\0\57\0\57\0\57\0\57\0\u3629"+
    "\0\57\0\57\0\57\0\u35fa\0\u35cb\0\u35cb\0\57\0\u3658"+
    "\0\57\0\u3687\0\u35fa\0\274\0\274\0\274\0\274\0\274"+
    "\0\274\0\274\0\274\0\274\0\u36b6\0\u36e5\0\u3714\0\u3743"+
    "\0\274\0\274\0\u3772\0\u37a1\0\57\0\u37d0\0\57\0\u37a1"+
    "\0\u37d0\0\u37ff\0\274\0\u382e\0\274\0\u385d\0\u385d\0\57"+
    "\0\274\0\u388c\0\u38bb\0\u38ea\0\57\0\274";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[446];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\3\2\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\7\1\27"+
    "\1\30\1\31\1\32\2\7\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\2\1\50\1\51\60\0\1\3\60\0\1\5"+
    "\1\52\55\0\1\7\1\0\1\7\1\53\1\0\1\54"+
    "\1\55\2\0\27\7\61\0\1\56\22\0\1\57\1\0"+
    "\1\60\1\61\1\62\1\63\1\64\2\0\1\65\1\66"+
    "\1\67\1\70\1\71\1\0\1\72\2\0\1\73\1\74"+
    "\1\75\1\76\1\77\22\0\1\7\1\0\1\7\1\53"+
    "\1\0\1\54\1\55\1\0\1\100\23\7\1\101\3\7"+
    "\17\0\1\7\1\0\1\7\1\53\1\0\1\54\1\102"+
    "\1\0\1\103\6\7\1\104\20\7\17\0\1\7\1\0"+
    "\1\7\1\53\1\0\1\54\1\55\1\0\1\105\3\7"+
    "\1\106\6\7\1\107\14\7\17\0\1\7\1\0\1\7"+
    "\1\53\1\0\1\54\1\55\1\0\1\110\6\7\1\111"+
    "\11\7\1\112\2\7\1\113\3\7\17\0\1\7\1\0"+
    "\1\7\1\53\1\0\1\54\1\55\1\0\1\114\2\7"+
    "\1\115\5\7\1\116\16\7\17\0\1\7\1\0\1\7"+
    "\1\53\1\0\1\54\1\55\1\0\1\117\20\7\1\120"+
    "\6\7\17\0\1\7\1\0\1\7\1\53\1\0\1\54"+
    "\1\55\1\0\1\121\7\7\1\122\2\7\1\123\7\7"+
    "\1\124\4\7\17\0\1\7\1\0\1\7\1\53\1\0"+
    "\1\54\1\55\1\0\1\125\1\7\1\126\6\7\1\127"+
    "\6\7\1\130\7\7\17\0\1\7\1\0\1\7\1\53"+
    "\1\0\1\54\1\55\1\0\1\131\6\7\1\132\2\7"+
    "\1\133\1\134\14\7\17\0\1\7\1\0\1\7\1\53"+
    "\1\0\1\54\1\55\1\0\1\135\20\7\1\136\6\7"+
    "\17\0\1\7\1\0\1\7\1\53\1\0\1\54\1\55"+
    "\1\0\1\137\6\7\1\140\20\7\17\0\1\7\1\0"+
    "\1\7\1\53\1\0\1\54\1\55\1\0\1\72\14\7"+
    "\1\141\12\7\17\0\1\7\1\0\1\7\1\53\1\0"+
    "\1\54\1\55\1\0\1\142\1\143\17\7\1\144\1\145"+
    "\1\7\1\146\3\7\17\0\1\7\1\0\1\7\1\53"+
    "\1\0\1\54\1\55\1\0\1\147\6\7\1\150\20\7"+
    "\17\0\1\7\1\0\1\7\1\53\1\0\1\54\1\55"+
    "\1\0\1\151\22\7\1\152\4\7\17\0\1\7\1\0"+
    "\1\7\1\53\1\0\1\54\1\55\1\0\1\153\12\7"+
    "\1\154\4\7\1\155\3\7\1\156\3\7\17\0\1\7"+
    "\1\0\1\7\1\53\1\0\1\54\1\55\1\0\1\157"+
    "\10\7\1\160\16\7\17\0\1\7\1\0\1\7\1\53"+
    "\1\0\1\54\1\55\1\0\1\161\10\7\1\162\16\7"+
    "\17\0\1\7\1\0\1\7\1\53\1\0\1\54\1\55"+
    "\1\0\1\163\20\7\1\164\6\7\17\0\1\7\1\0"+
    "\1\7\1\53\1\0\1\54\1\55\1\0\1\165\20\7"+
    "\1\166\6\7\14\0\1\46\1\0\55\46\1\167\1\0"+
    "\51\167\1\170\1\171\2\167\55\0\1\50\10\0\1\172"+
    "\35\0\1\173\14\0\1\174\60\0\1\175\1\0\1\176"+
    "\4\0\27\175\21\0\1\177\6\0\27\177\26\0\1\200"+
    "\47\0\1\201\66\0\1\202\1\203\1\204\1\205\1\206"+
    "\1\207\1\210\1\211\1\212\1\213\1\214\1\215\2\0"+
    "\1\216\1\0\1\217\1\220\1\221\1\222\1\223\32\0"+
    "\1\206\3\0\1\206\52\0\1\224\23\0\1\224\32\0"+
    "\1\210\5\0\1\210\50\0\1\225\1\0\1\204\7\0"+
    "\1\226\3\0\1\227\40\0\1\230\6\0\1\231\2\0"+
    "\1\232\3\0\1\233\3\0\1\221\34\0\1\234\7\0"+
    "\1\234\46\0\1\235\4\0\1\236\2\0\1\237\2\0"+
    "\1\215\2\0\1\240\40\0\1\241\2\0\1\242\5\0"+
    "\1\243\45\0\2\203\14\0\1\244\40\0\1\245\2\0"+
    "\1\246\1\0\1\247\1\0\1\250\6\0\1\251\5\0"+
    "\1\252\32\0\1\253\22\0\1\253\33\0\1\254\4\0"+
    "\1\255\15\0\1\256\33\0\1\257\6\0\1\260\1\0"+
    "\1\261\6\0\1\217\1\220\35\0\1\262\6\0\1\260"+
    "\1\0\1\261\35\0\1\7\1\0\1\7\1\53\1\0"+
    "\1\54\1\55\1\0\1\262\6\7\1\263\1\7\1\264"+
    "\16\7\17\0\1\201\6\0\1\200\57\0\1\265\11\0"+
    "\1\265\34\0\1\7\1\0\1\7\1\53\1\0\1\54"+
    "\1\55\1\0\1\265\11\7\1\266\15\7\27\0\1\267"+
    "\7\0\1\237\2\0\1\215\2\0\1\240\30\0\1\7"+
    "\1\0\1\7\1\53\1\0\1\54\1\55\1\0\1\267"+
    "\7\7\1\270\2\7\1\271\2\7\1\272\11\7\27\0"+
    "\1\273\11\0\1\274\6\0\1\220\2\0\1\252\22\0"+
    "\1\7\1\0\1\7\1\53\1\0\1\54\1\55\1\0"+
    "\1\274\11\7\1\275\15\7\17\0\1\7\1\0\1\7"+
    "\1\53\1\0\1\54\1\55\1\0\1\252\23\7\1\276"+
    "\3\7\17\0\1\7\1\0\1\7\1\53\1\0\1\54"+
    "\1\55\1\0\1\220\20\7\1\277\6\7\27\0\1\300"+
    "\5\0\1\210\3\0\1\301\34\0\1\7\1\0\1\7"+
    "\1\53\1\0\1\54\1\55\1\0\1\210\5\7\1\302"+
    "\21\7\17\0\1\7\1\0\1\7\1\53\1\0\1\54"+
    "\1\55\1\0\1\301\11\7\1\303\15\7\27\0\1\247"+
    "\4\0\1\247\41\0\1\7\1\0\1\7\1\53\1\0"+
    "\1\54\1\55\1\0\1\247\4\7\1\304\22\7\27\0"+
    "\1\305\4\0\1\306\15\0\1\256\23\0\1\7\1\0"+
    "\1\7\1\53\1\0\1\54\1\55\1\0\1\306\4\7"+
    "\1\307\22\7\17\0\1\7\1\0\1\7\1\53\1\0"+
    "\1\54\1\55\1\0\1\256\22\7\1\310\4\7\27\0"+
    "\1\311\1\203\10\0\1\312\3\0\1\233\5\0\1\224"+
    "\22\0\1\7\1\0\1\7\1\53\1\0\1\54\1\55"+
    "\1\0\1\224\23\7\1\313\3\7\17\0\1\7\1\0"+
    "\1\7\1\53\1\0\1\54\1\55\1\0\1\314\11\7"+
    "\1\315\3\7\1\316\11\7\17\0\1\7\1\0\1\7"+
    "\1\53\1\0\1\54\1\55\1\0\1\203\1\317\26\7"+
    "\27\0\1\320\1\0\1\204\2\0\1\321\2\0\1\234"+
    "\36\0\1\7\1\0\1\7\1\53\1\0\1\54\1\55"+
    "\1\0\1\204\1\7\1\322\25\7\17\0\1\7\1\0"+
    "\1\7\1\53\1\0\1\54\1\55\1\0\1\234\7\7"+
    "\1\323\17\7\17\0\1\7\1\0\1\7\1\53\1\0"+
    "\1\54\1\55\1\0\1\321\4\7\1\324\22\7\27\0"+
    "\1\250\6\0\1\250\37\0\1\7\1\0\1\7\1\53"+
    "\1\0\1\54\1\55\1\0\1\250\6\7\1\325\20\7"+
    "\27\0\1\227\15\0\1\227\30\0\1\7\1\0\1\7"+
    "\1\53\1\0\1\54\1\55\1\0\1\227\15\7\1\326"+
    "\11\7\17\0\1\7\1\0\1\7\1\53\1\0\1\54"+
    "\1\55\1\0\1\241\2\7\1\327\5\7\1\330\16\7"+
    "\27\0\1\331\3\0\1\206\13\0\1\217\2\0\1\253"+
    "\23\0\1\7\1\0\1\7\1\53\1\0\1\54\1\55"+
    "\1\0\1\206\3\7\1\332\23\7\17\0\1\7\1\0"+
    "\1\7\1\53\1\0\1\54\1\55\1\0\1\253\22\7"+
    "\1\333\4\7\17\0\1\7\1\0\1\7\1\53\1\0"+
    "\1\54\1\55\1\0\1\217\17\7\1\334\7\7\27\0"+
    "\1\335\11\0\1\335\34\0\1\7\1\0\1\7\1\53"+
    "\1\0\1\54\1\55\1\0\1\335\11\7\1\336\15\7"+
    "\27\0\1\255\4\0\1\255\41\0\1\7\1\0\1\7"+
    "\1\53\1\0\1\54\1\55\1\0\1\255\4\7\1\337"+
    "\22\7\27\0\1\244\15\0\1\244\30\0\1\7\1\0"+
    "\1\7\1\53\1\0\1\54\1\55\1\0\1\244\15\7"+
    "\1\340\11\7\27\0\1\231\6\0\1\231\37\0\1\7"+
    "\1\0\1\7\1\53\1\0\1\54\1\55\1\0\1\231"+
    "\6\7\1\341\20\7\27\0\1\221\21\0\1\221\24\0"+
    "\1\7\1\0\1\7\1\53\1\0\1\54\1\55\1\0"+
    "\1\221\21\7\1\342\5\7\27\0\1\251\15\0\1\251"+
    "\30\0\1\7\1\0\1\7\1\53\1\0\1\54\1\55"+
    "\1\0\1\251\15\7\1\343\11\7\27\0\1\246\2\0"+
    "\1\246\43\0\1\7\1\0\1\7\1\53\1\0\1\54"+
    "\1\55\1\0\1\246\2\7\1\344\24\7\67\0\1\167"+
    "\3\0\1\167\1\0\51\167\1\345\1\171\2\167\3\0"+
    "\1\175\1\0\1\175\6\0\27\175\21\0\1\346\6\0"+
    "\27\346\17\0\1\177\1\0\1\177\6\0\27\177\17\0"+
    "\1\201\6\0\1\347\57\0\1\350\2\0\1\351\1\352"+
    "\1\353\1\354\1\355\1\356\1\357\1\360\1\361\1\362"+
    "\1\363\1\364\1\0\1\365\1\366\2\0\1\367\32\0"+
    "\1\363\14\0\1\363\41\0\1\370\11\0\1\371\1\372"+
    "\43\0\1\373\2\0\1\373\53\0\1\374\2\0\1\375"+
    "\1\352\2\0\1\376\1\377\3\0\1\362\1\0\1\364"+
    "\40\0\1\u0100\4\0\1\353\5\0\1\u0101\43\0\1\u0102"+
    "\10\0\1\u0102\45\0\1\u0103\6\0\1\u0104\14\0\1\367"+
    "\32\0\1\u0105\7\0\1\u0106\1\u0107\1\u0108\5\0\1\365"+
    "\36\0\1\u0109\10\0\1\u0109\45\0\1\u010a\2\0\1\u010b"+
    "\15\0\1\366\35\0\1\u010c\10\0\1\u010c\45\0\1\354"+
    "\5\0\1\354\50\0\1\u010d\10\0\1\u010d\45\0\1\u010e"+
    "\10\0\1\u010e\45\0\1\u010f\2\0\1\u010b\4\0\1\u0106"+
    "\1\0\1\u0108\2\0\1\363\2\0\1\365\36\0\1\u0110"+
    "\7\0\1\u0106\1\0\1\u0108\5\0\1\365\36\0\1\u010b"+
    "\2\0\1\u010b\53\0\1\u0111\4\0\1\353\3\0\1\u0107"+
    "\45\0\1\353\4\0\1\353\51\0\1\u0107\10\0\1\u0107"+
    "\45\0\1\u0112\10\0\1\u0112\45\0\1\u0113\2\0\1\u0114"+
    "\1\352\3\0\1\377\1\u0115\2\0\1\362\1\0\1\364"+
    "\2\0\1\366\35\0\1\u0116\2\0\1\u0114\1\352\3\0"+
    "\1\377\3\0\1\362\1\0\1\364\40\0\1\u0117\10\0"+
    "\1\u0117\45\0\1\366\20\0\1\366\35\0\1\371\11\0"+
    "\1\371\11\0\1\367\32\0\1\371\11\0\1\371\44\0"+
    "\1\367\23\0\1\367\32\0\1\u0118\2\0\1\u0119\1\0"+
    "\1\u011a\5\0\1\372\5\0\1\u011b\35\0\1\372\12\0"+
    "\1\372\43\0\1\u0119\2\0\1\u0119\53\0\1\u011a\4\0"+
    "\1\u011a\51\0\1\u011b\20\0\1\u011b\35\0\1\u011c\10\0"+
    "\1\u011c\45\0\1\u011d\6\0\1\376\1\0\1\u011e\45\0"+
    "\1\376\6\0\1\376\47\0\1\u011e\10\0\1\u011e\45\0"+
    "\1\u011f\5\0\1\354\1\u0104\1\0\1\u010c\1\0\1\u0101"+
    "\43\0\1\u0101\12\0\1\u0101\43\0\1\u0104\6\0\1\u0104"+
    "\47\0\1\u0120\6\0\1\u0104\3\0\1\u0101\33\0\1\7"+
    "\1\0\1\7\1\53\1\0\1\54\1\55\1\0\1\u0101"+
    "\12\7\1\u0121\14\7\17\0\1\7\1\0\1\7\1\53"+
    "\1\0\1\54\1\55\1\0\1\u0104\6\7\1\u0122\20\7"+
    "\27\0\1\u0108\11\0\1\u0108\34\0\1\7\1\0\1\7"+
    "\1\53\1\0\1\54\1\55\1\0\1\u0108\11\7\1\u0123"+
    "\15\7\27\0\1\u0124\10\0\1\u0115\7\0\1\366\25\0"+
    "\1\7\1\0\1\7\1\53\1\0\1\54\1\55\1\0"+
    "\1\u0117\10\7\1\u0125\16\7\17\0\1\7\1\0\1\7"+
    "\1\53\1\0\1\54\1\55\1\0\1\u0109\10\7\1\u0126"+
    "\16\7\17\0\1\7\1\0\1\7\1\53\1\0\1\54"+
    "\1\55\1\0\1\366\20\7\1\u0127\6\7\27\0\1\u0128"+
    "\5\0\1\354\1\0\1\u0106\46\0\1\u0106\7\0\1\u0106"+
    "\36\0\1\7\1\0\1\7\1\53\1\0\1\54\1\55"+
    "\1\0\1\u0106\7\7\1\u0129\17\7\17\0\1\7\1\0"+
    "\1\7\1\53\1\0\1\54\1\55\1\0\1\354\5\7"+
    "\1\u012a\21\7\27\0\1\u012b\10\0\1\u012b\35\0\1\7"+
    "\1\0\1\7\1\53\1\0\1\54\1\55\1\0\1\u012b"+
    "\10\7\1\u012c\16\7\17\0\1\7\1\0\1\7\1\53"+
    "\1\0\1\54\1\55\1\0\1\u0119\2\7\1\u012d\24\7"+
    "\17\0\1\7\1\0\1\7\1\53\1\0\1\54\1\55"+
    "\1\0\1\u011e\10\7\1\u012e\16\7\27\0\1\u012f\10\0"+
    "\1\u012f\45\0\1\u0130\10\0\1\u0130\35\0\1\7\1\0"+
    "\1\7\1\53\1\0\1\54\1\55\1\0\1\u010e\10\7"+
    "\1\u0131\16\7\17\0\1\7\1\0\1\7\1\53\1\0"+
    "\1\54\1\55\1\0\1\u0130\10\7\1\u0132\16\7\27\0"+
    "\1\u0133\2\0\1\u0114\1\352\3\0\1\377\1\u0112\2\0"+
    "\1\362\1\363\1\364\30\0\1\7\1\0\1\7\1\53"+
    "\1\0\1\54\1\55\1\0\1\363\14\7\1\u0134\12\7"+
    "\17\0\1\7\1\0\1\7\1\53\1\0\1\54\1\55"+
    "\1\0\1\u0112\10\7\1\u0135\16\7\17\0\1\7\1\0"+
    "\1\7\1\53\1\0\1\54\1\55\1\0\1\u0116\2\7"+
    "\1\u0136\1\u0137\3\7\1\u0138\3\7\1\u0139\1\7\1\u013a"+
    "\11\7\17\0\1\7\1\0\1\7\1\53\1\0\1\54"+
    "\1\55\1\0\1\u011a\4\7\1\u013b\22\7\17\0\1\7"+
    "\1\0\1\7\1\53\1\0\1\54\1\55\1\0\1\u010b"+
    "\2\7\1\u013c\24\7\17\0\1\7\1\0\1\7\1\53"+
    "\1\0\1\54\1\55\1\0\1\371\11\7\1\u013d\15\7"+
    "\17\0\1\7\1\0\1\7\1\53\1\0\1\54\1\55"+
    "\1\0\1\367\23\7\1\u013e\3\7\27\0\1\u013f\2\0"+
    "\1\373\5\0\1\u011c\35\0\1\7\1\0\1\7\1\53"+
    "\1\0\1\54\1\55\1\0\1\373\2\7\1\u0140\24\7"+
    "\17\0\1\7\1\0\1\7\1\53\1\0\1\54\1\55"+
    "\1\0\1\u011c\10\7\1\u0141\16\7\17\0\1\7\1\0"+
    "\1\7\1\53\1\0\1\54\1\55\1\0\1\u010c\10\7"+
    "\1\u0142\16\7\27\0\1\365\17\0\1\365\26\0\1\7"+
    "\1\0\1\7\1\53\1\0\1\54\1\55\1\0\1\365"+
    "\17\7\1\u0143\7\7\17\0\1\7\1\0\1\7\1\53"+
    "\1\0\1\54\1\55\1\0\1\376\6\7\1\u0144\20\7"+
    "\17\0\1\7\1\0\1\7\1\53\1\0\1\54\1\55"+
    "\1\0\1\353\4\7\1\u0145\22\7\17\0\1\7\1\0"+
    "\1\7\1\53\1\0\1\54\1\55\1\0\1\u011b\20\7"+
    "\1\u0146\6\7\17\0\1\7\1\0\1\7\1\53\1\0"+
    "\1\54\1\55\1\0\1\372\12\7\1\u0147\14\7\17\0"+
    "\1\346\1\0\1\346\6\0\27\346\27\0\1\u0148\1\0"+
    "\1\u0149\1\0\1\u014a\4\0\1\u014b\1\0\1\u014c\1\0"+
    "\1\u014d\1\u014e\1\u014f\1\u0150\1\u0151\1\u0152\1\0\1\u0153"+
    "\1\u0154\31\0\1\u0155\3\0\1\u014a\12\0\1\u014f\4\0"+
    "\1\u0156\32\0\1\u0151\20\0\1\u0151\35\0\1\u0157\15\0"+
    "\1\u0158\6\0\1\u0154\31\0\1\u0159\10\0\1\u015a\6\0"+
    "\1\u0150\36\0\1\u015b\1\0\1\u015c\6\0\1\u015d\1\0"+
    "\1\u014c\2\0\1\u014e\5\0\1\u015e\32\0\1\u015f\10\0"+
    "\1\u015f\45\0\1\u0160\1\0\1\u0160\54\0\1\u014d\14\0"+
    "\1\u014d\41\0\1\u0152\21\0\1\u0152\34\0\1\u0161\10\0"+
    "\1\u0161\45\0\1\u0162\10\0\1\u0162\45\0\1\u0156\23\0"+
    "\1\u0156\32\0\1\u0163\3\0\1\u014a\10\0\1\u014d\1\u0158"+
    "\1\0\1\u0150\1\u0151\1\u0152\34\0\1\u014a\3\0\1\u014a"+
    "\52\0\1\u0158\15\0\1\u0158\40\0\1\u0150\17\0\1\u0150"+
    "\36\0\1\u0164\23\0\1\u0164\32\0\1\u0154\10\0\1\u0162"+
    "\13\0\1\u0154\31\0\1\u0154\24\0\1\u0154\31\0\1\u0165"+
    "\1\0\1\u015c\6\0\1\u0166\4\0\1\u014e\40\0\1\u015a"+
    "\10\0\1\u015a\45\0\1\u0167\1\0\1\u015c\13\0\1\u014e"+
    "\40\0\1\u0168\23\0\1\u0168\32\0\1\u014f\16\0\1\u014f"+
    "\37\0\1\u014c\12\0\1\u014c\43\0\1\u015d\10\0\1\u015d"+
    "\45\0\1\u0169\10\0\1\u0166\5\0\1\u014f\37\0\1\u0166"+
    "\10\0\1\u0166\45\0\1\u016a\3\0\1\u016b\10\0\1\u014d"+
    "\2\0\1\u0150\1\u0151\1\u0152\1\0\1\u015e\32\0\1\u016b"+
    "\3\0\1\u016b\52\0\1\u015e\23\0\1\u015e\32\0\1\u016c"+
    "\3\0\1\u016b\10\0\1\u014d\2\0\1\u0150\1\u0151\1\u0152"+
    "\34\0\1\u016d\3\0\1\u016d\52\0\1\u016e\12\0\1\u014c"+
    "\2\0\1\u0158\40\0\1\u016f\1\0\1\u0160\22\0\1\u0154"+
    "\21\0\1\7\1\0\1\7\1\53\1\0\1\54\1\55"+
    "\1\0\1\u0160\1\7\1\u0170\25\7\17\0\1\7\1\0"+
    "\1\7\1\53\1\0\1\54\1\55\1\0\1\u0154\24\7"+
    "\1\u0171\2\7\17\0\1\7\1\0\1\7\1\53\1\0"+
    "\1\54\1\55\1\0\1\u0164\23\7\1\u0172\3\7\17\0"+
    "\1\7\1\0\1\7\1\53\1\0\1\54\1\55\1\0"+
    "\1\u0168\23\7\1\u0173\3\7\17\0\1\7\1\0\1\7"+
    "\1\53\1\0\1\54\1\55\1\0\1\u015a\10\7\1\u0174"+
    "\16\7\27\0\1\u014e\15\0\1\u014e\30\0\1\7\1\0"+
    "\1\7\1\53\1\0\1\54\1\55\1\0\1\u014e\15\7"+
    "\1\u0175\11\7\17\0\1\7\1\0\1\7\1\53\1\0"+
    "\1\54\1\55\1\0\1\u016d\3\7\1\u0176\23\7\17\0"+
    "\1\7\1\0\1\7\1\53\1\0\1\54\1\55\1\0"+
    "\1\u014c\12\7\1\u0177\14\7\27\0\1\u0178\1\0\1\u015c"+
    "\6\0\1\u015d\45\0\1\u015c\1\0\1\u015c\44\0\1\7"+
    "\1\0\1\7\1\53\1\0\1\54\1\55\1\0\1\u015d"+
    "\10\7\1\u0179\16\7\17\0\1\7\1\0\1\7\1\53"+
    "\1\0\1\54\1\55\1\0\1\u015c\1\7\1\u017a\25\7"+
    "\17\0\1\7\1\0\1\7\1\53\1\0\1\54\1\55"+
    "\1\0\1\u016b\3\7\1\u017b\23\7\17\0\1\7\1\0"+
    "\1\7\1\53\1\0\1\54\1\55\1\0\1\u0151\20\7"+
    "\1\u017c\6\7\17\0\1\7\1\0\1\7\1\53\1\0"+
    "\1\54\1\55\1\0\1\u0150\17\7\1\u017d\7\7\17\0"+
    "\1\7\1\0\1\7\1\53\1\0\1\54\1\55\1\0"+
    "\1\u014d\14\7\1\u017e\12\7\17\0\1\7\1\0\1\7"+
    "\1\53\1\0\1\54\1\55\1\0\1\u0152\21\7\1\u017f"+
    "\5\7\17\0\1\7\1\0\1\7\1\53\1\0\1\54"+
    "\1\55\1\0\1\u014f\16\7\1\u0180\10\7\17\0\1\7"+
    "\1\0\1\7\1\53\1\0\1\54\1\55\1\0\1\u015f"+
    "\10\7\1\u0181\16\7\17\0\1\7\1\0\1\7\1\53"+
    "\1\0\1\54\1\55\1\0\1\u0162\10\7\1\u0182\16\7"+
    "\17\0\1\7\1\0\1\7\1\53\1\0\1\54\1\55"+
    "\1\0\1\u0156\23\7\1\u0183\3\7\17\0\1\7\1\0"+
    "\1\7\1\53\1\0\1\54\1\55\1\0\1\u0161\10\7"+
    "\1\u0184\16\7\17\0\1\7\1\0\1\7\1\53\1\0"+
    "\1\54\1\55\1\0\1\u0158\15\7\1\u0185\11\7\27\0"+
    "\1\u0186\1\u0187\1\0\1\u0188\1\0\1\u0189\2\0\1\u018a"+
    "\1\u018b\1\0\1\u018c\1\0\1\u018d\1\u018e\3\0\1\u018f"+
    "\1\u0190\1\u0191\32\0\1\u018d\14\0\1\u018d\1\u018e\40\0"+
    "\1\u018f\21\0\1\u018f\34\0\1\u018c\7\0\1\u0192\2\0"+
    "\1\u018c\43\0\1\u0189\4\0\1\u0189\51\0\1\u0188\2\0"+
    "\1\u0188\53\0\1\u0193\10\0\1\u0193\45\0\1\u0194\10\0"+
    "\1\u0194\45\0\2\u0187\55\0\1\u0191\23\0\1\u0191\32\0"+
    "\1\u0190\22\0\1\u0190\33\0\1\u0195\7\0\1\u0196\5\0"+
    "\1\u0197\40\0\1\u0198\7\0\1\u0196\1\u0194\10\0\1\u018f"+
    "\34\0\1\u0196\7\0\1\u0196\46\0\1\u0199\10\0\1\u0199"+
    "\45\0\1\u018c\4\0\1\u0189\3\0\1\u0193\1\0\1\u018c"+
    "\2\0\1\u018e\40\0\1\u018e\15\0\1\u018e\40\0\1\u018c"+
    "\12\0\1\u018c\43\0\1\u0197\15\0\1\u0197\40\0\1\u018d"+
    "\14\0\1\u018d\41\0\1\u0192\7\0\1\u0192\46\0\1\u019a"+
    "\1\u0187\1\0\1\u0188\5\0\1\u0199\10\0\1\u018f\1\u0190"+
    "\1\u0191\32\0\1\u0193\7\0\1\u0192\1\u0193\4\0\1\u018e"+
    "\40\0\1\u0193\10\0\1\u0193\4\0\1\u018e\40\0\1\u019b"+
    "\7\0\1\u0192\1\u0194\45\0\1\u019a\1\u0187\1\0\1\u0188"+
    "\12\0\1\u0197\4\0\1\u0190\1\u0191\32\0\1\u019a\1\u0187"+
    "\1\0\1\u0188\17\0\1\u0190\1\u0191\32\0\1\u0189\4\0"+
    "\1\u0189\3\0\1\u0199\35\0\1\7\1\0\1\7\1\53"+
    "\1\0\1\54\1\55\1\0\1\u018d\14\7\1\u019c\12\7"+
    "\17\0\1\7\1\0\1\7\1\53\1\0\1\54\1\55"+
    "\1\0\1\u0197\15\7\1\u019d\11\7\17\0\1\7\1\0"+
    "\1\7\1\53\1\0\1\54\1\55\1\0\1\u0193\10\7"+
    "\1\u019e\16\7\17\0\1\7\1\0\1\7\1\53\1\0"+
    "\1\54\1\55\1\0\1\u018f\21\7\1\u019f\5\7\17\0"+
    "\1\7\1\0\1\7\1\53\1\0\1\54\1\55\1\0"+
    "\1\u0189\4\7\1\u01a0\22\7\27\0\1\u018c\12\0\1\u018c"+
    "\2\0\1\u018e\30\0\1\7\1\0\1\7\1\53\1\0"+
    "\1\54\1\55\1\0\1\u018c\12\7\1\u01a1\14\7\17\0"+
    "\1\7\1\0\1\7\1\53\1\0\1\54\1\55\1\0"+
    "\1\u018e\15\7\1\u01a2\11\7\17\0\1\7\1\0\1\7"+
    "\1\53\1\0\1\54\1\55\1\0\1\u0191\23\7\1\u01a3"+
    "\3\7\17\0\1\7\1\0\1\7\1\53\1\0\1\54"+
    "\1\55\1\0\1\u0187\1\u01a4\26\7\17\0\1\7\1\0"+
    "\1\7\1\53\1\0\1\54\1\55\1\0\1\u0188\2\7"+
    "\1\u01a5\24\7\17\0\1\7\1\0\1\7\1\53\1\0"+
    "\1\54\1\55\1\0\1\u0190\22\7\1\u01a6\4\7\17\0"+
    "\1\7\1\0\1\7\1\53\1\0\1\54\1\55\1\0"+
    "\1\u0194\10\7\1\u01a7\16\7\17\0\1\7\1\0\1\7"+
    "\1\53\1\0\1\54\1\55\1\0\1\u0196\7\7\1\u01a8"+
    "\17\7\17\0\1\7\1\0\1\7\1\53\1\0\1\54"+
    "\1\55\1\0\1\u0192\7\7\1\u01a9\17\7\17\0\1\7"+
    "\1\0\1\7\1\53\1\0\1\54\1\55\1\0\1\u0199"+
    "\10\7\1\u01aa\16\7\27\0\1\u01ab\1\0\1\u01ac\6\0"+
    "\1\u01ad\1\u01ae\3\0\1\u01af\40\0\1\u01ae\11\0\1\u01ae"+
    "\44\0\1\u01af\15\0\1\u01af\40\0\1\u01ac\1\0\1\u01ac"+
    "\54\0\1\u01ad\10\0\1\u01ad\45\0\1\u01b0\1\0\1\u01ac"+
    "\13\0\1\u01af\40\0\1\u01b1\10\0\1\u01ad\1\u01ae\34\0"+
    "\1\7\1\0\1\7\1\53\1\0\1\54\1\55\1\0"+
    "\1\u01ae\11\7\1\u01b2\15\7\17\0\1\7\1\0\1\7"+
    "\1\53\1\0\1\54\1\55\1\0\1\u01ad\10\7\1\u01b3"+
    "\16\7\17\0\1\7\1\0\1\7\1\53\1\0\1\54"+
    "\1\55\1\0\1\u01ac\1\7\1\u01b4\25\7\17\0\1\7"+
    "\1\0\1\7\1\53\1\0\1\54\1\55\1\0\1\u01af"+
    "\15\7\1\u01b5\11\7\27\0\1\u01b6\6\0\1\u01b7\1\0"+
    "\1\u01b8\45\0\1\u01b7\6\0\1\u01b7\47\0\1\u01b8\10\0"+
    "\1\u01b8\35\0\1\7\1\0\1\7\1\53\1\0\1\54"+
    "\1\55\1\0\1\u01b8\10\7\1\u01b9\16\7\17\0\1\7"+
    "\1\0\1\7\1\53\1\0\1\54\1\55\1\0\1\u01b7"+
    "\6\7\1\u01ba\20\7\27\0\1\u01bb\11\0\1\u01bb\34\0"+
    "\1\7\1\0\1\7\1\53\1\0\1\54\1\55\1\0"+
    "\1\u01bb\11\7\1\u01bc\15\7\27\0\1\u01bd\11\0\1\u01bd"+
    "\34\0\1\7\1\0\1\7\1\53\1\0\1\54\1\55"+
    "\1\0\1\u01bd\11\7\1\u01be\15\7\14\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[14617];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\2\1\1\11\1\1\1\11\26\1\7\11"+
    "\4\1\4\0\1\11\1\0\1\1\3\0\1\11\1\0"+
    "\1\11\2\0\1\1\2\0\1\1\2\0\1\1\1\0"+
    "\1\1\2\0\4\1\1\0\3\1\1\0\2\1\1\0"+
    "\5\1\1\0\3\1\1\0\3\1\1\0\1\1\1\0"+
    "\7\1\1\0\1\1\1\0\5\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\2\11\2\1\1\0\1\1\1\11\1\0\1\1\1\11"+
    "\3\0\1\1\1\11\5\0\1\1\2\0\1\11\1\0"+
    "\1\1\4\0\1\1\2\0\1\11\1\0\2\1\5\0"+
    "\1\11\1\1\4\0\1\11\10\0\2\1\1\0\1\1"+
    "\1\0\4\1\1\0\4\1\1\0\4\1\1\11\3\1"+
    "\1\0\5\1\2\0\7\1\1\0\3\1\1\0\11\1"+
    "\1\11\1\1\2\0\2\11\2\0\3\1\1\0\1\11"+
    "\2\0\1\11\1\0\1\1\1\0\1\11\5\0\1\1"+
    "\1\0\1\1\2\0\1\1\2\0\1\11\1\0\1\1"+
    "\1\0\1\11\1\1\1\0\3\1\1\11\1\1\4\0"+
    "\1\1\1\0\3\11\2\0\1\1\1\0\12\1\1\0"+
    "\3\1\2\0\30\1\1\0\2\1\7\0\1\1\1\11"+
    "\1\1\1\0\1\1\1\0\1\1\1\11\1\1\2\0"+
    "\1\1\1\11\2\0\1\11\1\1\1\0\2\1\1\0"+
    "\1\11\2\1\1\11\1\1\2\0\11\1\1\0\16\1"+
    "\1\11\1\0\1\11\2\1\4\11\1\0\3\11\1\0"+
    "\1\1\1\0\1\11\1\1\1\11\22\1\1\0\1\11"+
    "\1\0\1\11\7\1\1\0\1\11\2\1\1\0\1\1"+
    "\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[446];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  private BParser yyparser;

  public BYylex(java.io.Reader r, BParser yyparser) {
    this(r);
    this.yyparser = yyparser;
    this.yyline = 0;
  }
  public BYylex(String s, BParser yyparser) {
    this(s);
    this.yyparser = yyparser;
    this.yyline = 0;
  }
  BYylex(String s) {
    this(new StringReader(s)); 
  }
  private void lg(String s){
    //System.out.println(s);
  }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  BYylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  BYylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 172) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 45: 
          { lg("Else");return BParser.ELSE;
          }
        case 77: break;
        case 51: 
          { lg("INTO");return BParser.INTO;
          }
        case 78: break;
        case 32: 
          { return BParser.LTE;
          }
        case 79: break;
        case 70: 
          { return BParser.ENDFOR;
          }
        case 80: break;
        case 55: 
          { return BParser.LOAD;
          }
        case 81: break;
        case 1: 
          { lg("Token não identificado ["+yytext()+"]");
          }
        case 82: break;
        case 67: 
          { return BParser.BRANCH;
          }
        case 83: break;
        case 39: 
          { return BParser.AND;
          }
        case 84: break;
        case 49: 
          { lg("JOI");return BParser.JOIN;
          }
        case 85: break;
        case 7: 
          { lg(">");return BParser.GT;
          }
        case 86: break;
        case 19: 
          { lg("ponto");return BParser.POINT;
          }
        case 87: break;
        case 26: 
          { lg("As");return BParser.AS;
          }
        case 88: break;
        case 63: 
          { return BParser.APPEND;
          }
        case 89: break;
        case 61: 
          { return BParser.WHERE;
          }
        case 90: break;
        case 56: 
          { lg("Endif");return BParser.ENDIF;
          }
        case 91: break;
        case 16: 
          { return BParser.PLUS;
          }
        case 92: break;
        case 35: 
          { lg(yytext());yyparser.yylval = new ParserVal(yytext());return BParser.NAMESQLJ;
          }
        case 93: break;
        case 75: 
          { return BParser.ENDWHILE;
          }
        case 94: break;
        case 3: 
          { yyparser.yylval = new ParserVal(new Variant(Integer.parseInt(yytext()))); return BParser.NUMINT;
          }
        case 95: break;
        case 53: 
          { return BParser.TYPE;
          }
        case 96: break;
        case 11: 
          { lg(yytext());yyparser.yylval = new ParserVal(yytext());return BParser.TYPEF;
          }
        case 97: break;
        case 66: 
          { return BParser.SCREEN;
          }
        case 98: break;
        case 41: 
          { return BParser.KEY;
          }
        case 99: break;
        case 44: 
          { lg(yytext());yyparser.yylval = new ParserVal(yytext());return BParser.CALLPROG;
          }
        case 100: break;
        case 6: 
          { return BParser.MINUS;
          }
        case 101: break;
        case 5: 
          { lg(yytext());yyparser.yylval = new ParserVal(yytext());return BParser.NAME;
          }
        case 102: break;
        case 47: 
          { lg("FRM");return BParser.FROM;
          }
        case 103: break;
        case 28: 
          { return BParser.TO;
          }
        case 104: break;
        case 50: 
          { return BParser.EACH;
          }
        case 105: break;
        case 65: 
          { return BParser.DELETE;
          }
        case 106: break;
        case 36: 
          { lg(yytext());yyparser.yylval = new ParserVal(yytext());return BParser.TABLE;
          }
        case 107: break;
        case 64: 
          { lg("VAL");return BParser.VALUES;
          }
        case 108: break;
        case 17: 
          { return BParser.DIV;
          }
        case 109: break;
        case 74: 
          { return BParser.TBFIRST;
          }
        case 110: break;
        case 15: 
          { return BParser.EQ;
          }
        case 111: break;
        case 59: 
          { return BParser.BREAK;
          }
        case 112: break;
        case 12: 
          { lg(yytext());yyparser.yylval = new ParserVal(yytext());return BParser.TYPED;
          }
        case 113: break;
        case 29: 
          { lg("ON");return BParser.ON;
          }
        case 114: break;
        case 58: 
          { lg("INN");return BParser.INNER;
          }
        case 115: break;
        case 33: 
          { lg("FLOAT: "+yytext());yyparser.yylval = new ParserVal(new Variant(Float.parseFloat(yytext().replace(',','.')))); return BParser.NUMFLT;
          }
        case 116: break;
        case 37: 
          { lg("Dim");return BParser.DIM;
          }
        case 117: break;
        case 73: 
          { return BParser.ENDTYPE;
          }
        case 118: break;
        case 31: 
          { return BParser.NEQ;
          }
        case 119: break;
        case 54: 
          { return BParser.GOTO;
          }
        case 120: break;
        case 72: 
          { lg("upd");return BParser.UPDATE;
          }
        case 121: break;
        case 40: 
          { return BParser.OUT;
          }
        case 122: break;
        case 20: 
          { lg("Comentário:"+yytext());return BParser.COMMENT;
          }
        case 123: break;
        case 46: 
          { return BParser.READ;
          }
        case 124: break;
        case 38: 
          { return BParser.SUB;
          }
        case 125: break;
        case 14: 
          { return BParser.RPAR;
          }
        case 126: break;
        case 4: 
          { return BParser.COMMA;
          }
        case 127: break;
        case 9: 
          { lg(yytext());yyparser.yylval = new ParserVal(yytext());return BParser.TYPEC;
          }
        case 128: break;
        case 10: 
          { lg(yytext());yyparser.yylval = new ParserVal(yytext());return BParser.TYPEI;
          }
        case 129: break;
        case 22: 
          { return BParser.LT;
          }
        case 130: break;
        case 71: 
          { lg("INS");return BParser.INSERT;
          }
        case 131: break;
        case 48: 
          { return BParser.CALL;
          }
        case 132: break;
        case 68: 
          { lg("SEL");return BParser.SELECT;
          }
        case 133: break;
        case 25: 
          { lg("If");return BParser.IF;
          }
        case 134: break;
        case 30: 
          { lg("String:"+yytext());yyparser.yylval = new ParserVal(new Variant(yytext().replaceAll("\"","")));return BParser.STRING;
          }
        case 135: break;
        case 62: 
          { return BParser.ENDSUB;
          }
        case 136: break;
        case 27: 
          { return BParser.IN;
          }
        case 137: break;
        case 13: 
          { return BParser.LPAR;
          }
        case 138: break;
        case 18: 
          { return BParser.TIMES;
          }
        case 139: break;
        case 52: 
          { return BParser.TRUE;
          }
        case 140: break;
        case 34: 
          { lg(yytext());yyparser.yylval = new ParserVal(yytext());return BParser.FIELD;
          }
        case 141: break;
        case 8: 
          { lg(yytext());yyparser.yylval = new ParserVal(yytext());return BParser.TYPEB;
          }
        case 142: break;
        case 23: 
          { return BParser.GTE;
          }
        case 143: break;
        case 42: 
          { return BParser.FOR;
          }
        case 144: break;
        case 76: 
          { return BParser.NATIVECALL;
          }
        case 145: break;
        case 69: 
          { lg("mdf");return BParser.MODIFY;
          }
        case 146: break;
        case 60: 
          { return BParser.FALSE;
          }
        case 147: break;
        case 2: 
          { yyline++;lg("ENTER");return BParser.NL;
          }
        case 148: break;
        case 24: 
          { return BParser.OR;
          }
        case 149: break;
        case 21: 
          { 
          }
        case 150: break;
        case 57: 
          { lg("While");return BParser.WHILE;
          }
        case 151: break;
        case 43: 
          { lg("SET");return BParser.SET;
          }
        case 152: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return 0; }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
